//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.NM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.NM.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop action.
        /// </summary>
        public static string activity_getelement_loopaction {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this, once done processing each result, then reruns the selector and looks for new items.
        /// </summary>
        public static string activity_getelement_loopaction_tooltop {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction_tooltop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an browser element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Editor.
        /// </summary>
        public static string activity_open_editor {
            get {
                return ResourceManager.GetString("activity_open_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL.
        /// </summary>
        public static string activity_openurl {
            get {
                return ResourceManager.GetString("activity_openurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current.
        /// </summary>
        public static string activity_openurl_getcurrent {
            get {
                return ResourceManager.GetString("activity_openurl_getcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the specefied url in the selected browser.
        /// </summary>
        public static string activity_openurl_tooltip {
            get {
                return ResourceManager.GetString("activity_openurl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for ready.
        /// </summary>
        public static string activity_waitforready {
            get {
                return ResourceManager.GetString("activity_waitforready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for page page to be ready / is not loading.
        /// </summary>
        public static string activity_waitforready_help {
            get {
                return ResourceManager.GetString("activity_waitforready_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate for old extension.
        /// </summary>
        public static string compensate_for_old_addon {
            get {
                return ResourceManager.GetString("compensate_for_old_addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pixel compensation for old add.
        /// </summary>
        public static string compensate_for_old_addon_help {
            get {
                return ResourceManager.GetString("compensate_for_old_addon_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Console.
        /// </summary>
        public static string debug_console_output {
            get {
                return ResourceManager.GetString("debug_console_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write debug informtation to browser console.
        /// </summary>
        public static string debug_console_output_help {
            get {
                return ResourceManager.GetString("debug_console_output_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait after set value.
        /// </summary>
        public static string plugin_wait_for_tab_after_set_value {
            get {
                return ResourceManager.GetString("plugin_wait_for_tab_after_set_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for tab status to be in ready state after setting a value.
        /// </summary>
        public static string plugin_wait_for_tab_after_set_value_help {
            get {
                return ResourceManager.GetString("plugin_wait_for_tab_after_set_value_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register old portname.
        /// </summary>
        public static string register_old_portname {
            get {
                return ResourceManager.GetString("register_old_portname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register old browser extension port names .
        /// </summary>
        public static string register_old_portname_help {
            get {
                return ResourceManager.GetString("register_old_portname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unique ids.
        /// </summary>
        public static string unique_xpath_ids {
            get {
                return ResourceManager.GetString("unique_xpath_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use on of these attributes as unique id&apos;s when creating xpath selectors.
        /// </summary>
        public static string unique_xpath_ids_help {
            get {
                return ResourceManager.GetString("unique_xpath_ids_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait for tab.
        /// </summary>
        public static string wait_for_tab_click {
            get {
                return ResourceManager.GetString("wait_for_tab_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for tab status to be in ready state after clicking a button.
        /// </summary>
        public static string wait_for_tab_click_help {
            get {
                return ResourceManager.GetString("wait_for_tab_click_help", resourceCulture);
            }
        }
    }
}
