//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.RDServicePlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.RDServicePlugin.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Signout.
        /// </summary>
        public static string plugin_auto_signout {
            get {
                return ResourceManager.GetString("plugin_auto_signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add current user.
        /// </summary>
        public static string plugin_button_add_user {
            get {
                return ResourceManager.GetString("plugin_button_add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        public static string plugin_button_install_service {
            get {
                return ResourceManager.GetString("plugin_button_install_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate Service.
        /// </summary>
        public static string plugin_button_reauth {
            get {
                return ResourceManager.GetString("plugin_button_reauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove current user.
        /// </summary>
        public static string plugin_button_remove_user {
            get {
                return ResourceManager.GetString("plugin_button_remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        public static string plugin_button_start_service {
            get {
                return ResourceManager.GetString("plugin_button_start_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        public static string plugin_button_stop_service {
            get {
                return ResourceManager.GetString("plugin_button_stop_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Service.
        /// </summary>
        public static string plugin_button_uninstall_service {
            get {
                return ResourceManager.GetString("plugin_button_uninstall_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string plugin_executable {
            get {
                return ResourceManager.GetString("plugin_executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload interval.
        /// </summary>
        public static string plugin_reload_interval {
            get {
                return ResourceManager.GetString("plugin_reload_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Free RDP.
        /// </summary>
        public static string plugin_use_free_rdp {
            get {
                return ResourceManager.GetString("plugin_use_free_rdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Password.
        /// </summary>
        public static string plugin_windows_password {
            get {
                return ResourceManager.GetString("plugin_windows_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Username.
        /// </summary>
        public static string plugin_windows_username {
            get {
                return ResourceManager.GetString("plugin_windows_username", resourceCulture);
            }
        }
    }
}
