//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Elis.Rossum.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Elis.Rossum.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Email.
        /// </summary>
        public static string activity_auth_hint {
            get {
                return ResourceManager.GetString("activity_auth_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string activity_auth_username {
            get {
                return ResourceManager.GetString("activity_auth_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileURL.
        /// </summary>
        public static string activity_exportfile_file {
            get {
                return ResourceManager.GetString("activity_exportfile_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to file to get data from.
        /// </summary>
        public static string activity_exportfile_file_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_exportfile_key {
            get {
                return ResourceManager.GetString("activity_exportfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key from auth activitity.
        /// </summary>
        public static string activity_exportfile_key_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string activity_exportfile_queue {
            get {
                return ResourceManager.GetString("activity_exportfile_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue to export data from.
        /// </summary>
        public static string activity_exportfile_queue_hint {
            get {
                return ResourceManager.GetString("activity_exportfile_queue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_getqueues_key {
            get {
                return ResourceManager.GetString("activity_getqueues_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key from auth activitity.
        /// </summary>
        public static string activity_getqueues_key_hint {
            get {
                return ResourceManager.GetString("activity_getqueues_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileURL.
        /// </summary>
        public static string activity_getstatus_file {
            get {
                return ResourceManager.GetString("activity_getstatus_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to file to get status from.
        /// </summary>
        public static string activity_getstatus_file_hint {
            get {
                return ResourceManager.GetString("activity_getstatus_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_getstatus_key {
            get {
                return ResourceManager.GetString("activity_getstatus_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key from auth activitity.
        /// </summary>
        public static string activity_getstatus_key_hint {
            get {
                return ResourceManager.GetString("activity_getstatus_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_uploadfile_filename {
            get {
                return ResourceManager.GetString("activity_uploadfile_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File to upload to the queue.
        /// </summary>
        public static string activity_uploadfile_filename_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_uploadfile_key {
            get {
                return ResourceManager.GetString("activity_uploadfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key from auth activitity.
        /// </summary>
        public static string activity_uploadfile_key_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string activity_uploadfile_queue {
            get {
                return ResourceManager.GetString("activity_uploadfile_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue to upload the file to.
        /// </summary>
        public static string activity_uploadfile_queue_hint {
            get {
                return ResourceManager.GetString("activity_uploadfile_queue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileURL.
        /// </summary>
        public static string activity_waitforfile_file {
            get {
                return ResourceManager.GetString("activity_waitforfile_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to file to wait for.
        /// </summary>
        public static string activity_waitforfile_file_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_file_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_waitforfile_key {
            get {
                return ResourceManager.GetString("activity_waitforfile_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key from auth activitity.
        /// </summary>
        public static string activity_waitforfile_key_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_key_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string activity_waitforfile_status {
            get {
                return ResourceManager.GetString("activity_waitforfile_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status to wait for.
        /// </summary>
        public static string activity_waitforfile_status_hint {
            get {
                return ResourceManager.GetString("activity_waitforfile_status_hint", resourceCulture);
            }
        }
    }
}
