//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.WorkItems.Activities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.WorkItems.Activities.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Workitem.
        /// </summary>
        public static string activity_addworkitem {
            get {
                return ResourceManager.GetString("activity_addworkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Queue.
        /// </summary>
        public static string activity_addworkitem_failed_wiq {
            get {
                return ResourceManager.GetString("activity_addworkitem_failed_wiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If failed, add new workitem to this queue.
        /// </summary>
        public static string activity_addworkitem_failed_wiq_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_failed_wiq_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string activity_addworkitem_files {
            get {
                return ResourceManager.GetString("activity_addworkitem_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add these files to new Workitem.
        /// </summary>
        public static string activity_addworkitem_files_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_files_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string activity_addworkitem_name {
            get {
                return ResourceManager.GetString("activity_addworkitem_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom name of Workitem.
        /// </summary>
        public static string activity_addworkitem_name_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_name_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Run.
        /// </summary>
        public static string activity_addworkitem_nextrun {
            get {
                return ResourceManager.GetString("activity_addworkitem_nextrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default Workitems run right away or with the number of seconds delay set in initial delay on the queue. Use this field to only run the Work Item after the given datetime.
        /// </summary>
        public static string activity_addworkitem_nextrun_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_nextrun_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string activity_addworkitem_payload {
            get {
                return ResourceManager.GetString("activity_addworkitem_payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of values to add to Workitem payload, these can be read and updated as part of the processing using Update Workitem.
        /// </summary>
        public static string activity_addworkitem_payload_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_payload_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string activity_addworkitem_priority {
            get {
                return ResourceManager.GetString("activity_addworkitem_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set priority to a non zero number for this item. The lower the number the higher the proirity.
        /// </summary>
        public static string activity_addworkitem_priority_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_priority_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string activity_addworkitem_result {
            get {
                return ResourceManager.GetString("activity_addworkitem_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resulting Work item.
        /// </summary>
        public static string activity_addworkitem_result_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Queue.
        /// </summary>
        public static string activity_addworkitem_success_wiq {
            get {
                return ResourceManager.GetString("activity_addworkitem_success_wiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If successfull, add new workitem to this queue.
        /// </summary>
        public static string activity_addworkitem_success_wiq_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_success_wiq_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Workitem to Queue.
        /// </summary>
        public static string activity_addworkitem_tooltip {
            get {
                return ResourceManager.GetString("activity_addworkitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Name.
        /// </summary>
        public static string activity_addworkitem_wiq {
            get {
                return ResourceManager.GetString("activity_addworkitem_wiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of queue to add Workitem too.
        /// </summary>
        public static string activity_addworkitem_wiq_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_wiq_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue ID.
        /// </summary>
        public static string activity_addworkitem_wiqid {
            get {
                return ResourceManager.GetString("activity_addworkitem_wiqid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of queue to add Workitem too.
        /// </summary>
        public static string activity_addworkitem_wiqid_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_wiqid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem.
        /// </summary>
        public static string activity_addworkitem_workitem {
            get {
                return ResourceManager.GetString("activity_addworkitem_workitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The added Workitem.
        /// </summary>
        public static string activity_addworkitem_workitem_help {
            get {
                return ResourceManager.GetString("activity_addworkitem_workitem_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Add Workitems.
        /// </summary>
        public static string activity_bulkaddworkitems {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Size.
        /// </summary>
        public static string activity_bulkaddworkitems_bulksize {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_bulksize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workitems in batches of this size. The bigger the payload and files, the loweer this number should be. Default is 50.
        /// </summary>
        public static string activity_bulkaddworkitems_bulksize_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_bulksize_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string activity_bulkaddworkitems_datatable {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable containing the data to be used for creating the Workitems..
        /// </summary>
        public static string activity_bulkaddworkitems_datatable_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_datatable_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Columns.
        /// </summary>
        public static string activity_bulkaddworkitems_filefields {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_filefields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of Column names that contains full path and filename to be attached to that workitem.
        /// </summary>
        public static string activity_bulkaddworkitems_filefields_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_filefields_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/open-rpa/openrpa/wiki/Workitems#bulk-add-workitems.
        /// </summary>
        public static string activity_bulkaddworkitems_helpurl {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Run.
        /// </summary>
        public static string activity_bulkaddworkitems_nextrun {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_nextrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default Workitems run right away or with the number of seconds delay set in initial delay on the queue. Use this field to only run the Work Item after the given datetime.
        /// </summary>
        public static string activity_bulkaddworkitems_nextrun_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_nextrun_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string activity_bulkaddworkitems_priority {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set priority to a non zero number for this item. The lower the number the higher the proirity.
        /// </summary>
        public static string activity_bulkaddworkitems_priority_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_priority_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Workitem for each row in a DataTable.
        /// </summary>
        public static string activity_bulkaddworkitems_tooltip {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Name.
        /// </summary>
        public static string activity_bulkaddworkitems_wiq {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_wiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of queue to add Workitem too.
        /// </summary>
        public static string activity_bulkaddworkitems_wiq_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_wiq_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue ID.
        /// </summary>
        public static string activity_bulkaddworkitems_wiqid {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_wiqid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of queue to add Workitem too.
        /// </summary>
        public static string activity_bulkaddworkitems_wiqid_help {
            get {
                return ResourceManager.GetString("activity_bulkaddworkitems_wiqid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Workitem.
        /// </summary>
        public static string activity_deleteworkitem {
            get {
                return ResourceManager.GetString("activity_deleteworkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete specific Workitem and all associated files from queue. Generally this should never be used.
        /// </summary>
        public static string activity_deleteworkitem_tooltip {
            get {
                return ResourceManager.GetString("activity_deleteworkitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem.
        /// </summary>
        public static string activity_deleteworkitem_workitem {
            get {
                return ResourceManager.GetString("activity_deleteworkitem_workitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem to be deleted.
        /// </summary>
        public static string activity_deleteworkitem_workitem_help {
            get {
                return ResourceManager.GetString("activity_deleteworkitem_workitem_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname inside the workflow designer.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Variables.
        /// </summary>
        public static string activity_map_variables {
            get {
                return ResourceManager.GetString("activity_map_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop Workitem.
        /// </summary>
        public static string activity_popworkitem {
            get {
                return ResourceManager.GetString("activity_popworkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string activity_popworkitem_folder {
            get {
                return ResourceManager.GetString("activity_popworkitem_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default workitem files are saved in project folder, set this to override where to save WorkItem files.
        /// </summary>
        public static string activity_popworkitem_folder_help {
            get {
                return ResourceManager.GetString("activity_popworkitem_folder_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/open-rpa/openrpa/wiki/Workitems#pop-workitem.
        /// </summary>
        public static string activity_popworkitem_helpurl {
            get {
                return ResourceManager.GetString("activity_popworkitem_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string activity_popworkitem_result {
            get {
                return ResourceManager.GetString("activity_popworkitem_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result will contain the Workitem checked out to you, returns nothing if no more items.
        /// </summary>
        public static string activity_popworkitem_result_help {
            get {
                return ResourceManager.GetString("activity_popworkitem_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch and checkout next Workitem to work on, remember to update state with Update Workitem.
        /// </summary>
        public static string activity_popworkitem_tooltip {
            get {
                return ResourceManager.GetString("activity_popworkitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Name.
        /// </summary>
        public static string activity_popworkitem_wiq {
            get {
                return ResourceManager.GetString("activity_popworkitem_wiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of queue to pop an Workitem from.
        /// </summary>
        public static string activity_popworkitem_wiq_help {
            get {
                return ResourceManager.GetString("activity_popworkitem_wiq_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue ID.
        /// </summary>
        public static string activity_popworkitem_wiqid {
            get {
                return ResourceManager.GetString("activity_popworkitem_wiqid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of queue to pop an Workitem from.
        /// </summary>
        public static string activity_popworkitem_wiqid_help {
            get {
                return ResourceManager.GetString("activity_popworkitem_wiqid_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem.
        /// </summary>
        public static string activity_popworkitem_workitem {
            get {
                return ResourceManager.GetString("activity_popworkitem_workitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Workitem checked out to you, returns nothing if no more items.
        /// </summary>
        public static string activity_popworkitem_workitem_help {
            get {
                return ResourceManager.GetString("activity_popworkitem_workitem_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw Business Rule Exception.
        /// </summary>
        public static string activity_throwbusinessruleexception {
            get {
                return ResourceManager.GetString("activity_throwbusinessruleexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/open-rpa/openrpa/wiki/Workitems#throw-business-rule-exception.
        /// </summary>
        public static string activity_throwbusinessruleexception_helpurl {
            get {
                return ResourceManager.GetString("activity_throwbusinessruleexception_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string activity_throwbusinessruleexception_message {
            get {
                return ResourceManager.GetString("activity_throwbusinessruleexception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short describtion of why this workflow failed due to an Business Rule Exception. What data was missing, incomplete or invalid ? We recommend using payload for more detailed information.
        /// </summary>
        public static string activity_throwbusinessruleexception_message_help {
            get {
                return ResourceManager.GetString("activity_throwbusinessruleexception_message_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw a Business Rule Exception. The workflow is failing due to missing, incomplete or invalid data.
        /// </summary>
        public static string activity_throwbusinessruleexception_tooltip {
            get {
                return ResourceManager.GetString("activity_throwbusinessruleexception_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Workitem.
        /// </summary>
        public static string activity_updateworkitem {
            get {
                return ResourceManager.GetString("activity_updateworkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string activity_updateworkitem_exception {
            get {
                return ResourceManager.GetString("activity_updateworkitem_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach exception to Workitem in case of error.
        /// </summary>
        public static string activity_updateworkitem_exception_help {
            get {
                return ResourceManager.GetString("activity_updateworkitem_exception_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string activity_updateworkitem_files {
            get {
                return ResourceManager.GetString("activity_updateworkitem_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or Update files associated with this Workitem.
        /// </summary>
        public static string activity_updateworkitem_files_help {
            get {
                return ResourceManager.GetString("activity_updateworkitem_files_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Max Retries.
        /// </summary>
        public static string activity_updateworkitem_ignoremaxretries {
            get {
                return ResourceManager.GetString("activity_updateworkitem_ignoremaxretries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default a Workitem will fail, once max retries has been reached. Set this to true to resubmit even if max retries have been reached.
        /// </summary>
        public static string activity_updateworkitem_ignoremaxretries_help {
            get {
                return ResourceManager.GetString("activity_updateworkitem_ignoremaxretries_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string activity_updateworkitem_state {
            get {
                return ResourceManager.GetString("activity_updateworkitem_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Workitem&apos;s state to this value.
        /// </summary>
        public static string activity_updateworkitem_state_help {
            get {
                return ResourceManager.GetString("activity_updateworkitem_state_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Workitem set set state, update files and/or update payload.
        /// </summary>
        public static string activity_updateworkitem_tooltip {
            get {
                return ResourceManager.GetString("activity_updateworkitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workitem.
        /// </summary>
        public static string activity_updateworkitem_workitem {
            get {
                return ResourceManager.GetString("activity_updateworkitem_workitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Workitem, remember to set state.
        /// </summary>
        public static string activity_updateworkitem_workitem_help {
            get {
                return ResourceManager.GetString("activity_updateworkitem_workitem_help", resourceCulture);
            }
        }
    }
}
