//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Selenium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Selenium.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Driver.
        /// </summary>
        public static string activity_closedriver {
            get {
                return ResourceManager.GetString("activity_closedriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep browser open.
        /// </summary>
        public static string activity_CloseDriver_KillDriver {
            get {
                return ResourceManager.GetString("activity_CloseDriver_KillDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Tab.
        /// </summary>
        public static string activity_closetab {
            get {
                return ResourceManager.GetString("activity_closetab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.openiap.io/openrpa.html#openrpa-nm.
        /// </summary>
        public static string activity_closetab_helpurl {
            get {
                return ResourceManager.GetString("activity_closetab_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the current tab, or close all tabs.
        /// </summary>
        public static string activity_closetab_tooltip {
            get {
                return ResourceManager.GetString("activity_closetab_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname inside the workflow designer.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Actions.
        /// </summary>
        public static string activity_elementactions {
            get {
                return ResourceManager.GetString("activity_elementactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string activity_elementactions_action {
            get {
                return ResourceManager.GetString("activity_elementactions_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument.
        /// </summary>
        public static string activity_elementactions_argument {
            get {
                return ResourceManager.GetString("activity_elementactions_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input argument for action..
        /// </summary>
        public static string activity_elementactions_argument_hint {
            get {
                return ResourceManager.GetString("activity_elementactions_argument_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Actions.
        /// </summary>
        public static string activity_elementactions_helpurl {
            get {
                return ResourceManager.GetString("activity_elementactions_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Actions.
        /// </summary>
        public static string activity_elementactions_tooltip {
            get {
                return ResourceManager.GetString("activity_elementactions_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Javascript.
        /// </summary>
        public static string activity_executejavascript {
            get {
                return ResourceManager.GetString("activity_executejavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute type to choose.
        /// </summary>
        public static string activity_executejavascript_choose_executetype {
            get {
                return ResourceManager.GetString("activity_executejavascript_choose_executetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input script to execute.
        /// </summary>
        public static string activity_executejavascript_choose_executetype_hint {
            get {
                return ResourceManager.GetString("activity_executejavascript_choose_executetype_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script to execute.
        /// </summary>
        public static string activity_executejavascript_choose_executetype_script {
            get {
                return ResourceManager.GetString("activity_executejavascript_choose_executetype_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Script.
        /// </summary>
        public static string activity_executescript {
            get {
                return ResourceManager.GetString("activity_executescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.openiap.io/openrpa.html#openrpa-nm.
        /// </summary>
        public static string activity_executescript_helpurl {
            get {
                return ResourceManager.GetString("activity_executescript_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute script in the browser, targeting current tab and default frame.
        /// </summary>
        public static string activity_executescript_tooltip {
            get {
                return ResourceManager.GetString("activity_executescript_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element Async.
        /// </summary>
        public static string activity_getelement_async {
            get {
                return ResourceManager.GetString("activity_getelement_async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an browser elements based on selector.
        /// </summary>
        public static string activity_getelement_async_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_async_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Elements By.
        /// </summary>
        public static string activity_getelement_findby {
            get {
                return ResourceManager.GetString("activity_getelement_findby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value To Find Elements.
        /// </summary>
        public static string activity_getelement_findvalue {
            get {
                return ResourceManager.GetString("activity_getelement_findvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value to find elements..
        /// </summary>
        public static string activity_getelement_findvalue_hint {
            get {
                return ResourceManager.GetString("activity_getelement_findvalue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.openiap.io/openrpa.html#openrpa-nm.
        /// </summary>
        public static string activity_getelement_helpurl {
            get {
                return ResourceManager.GetString("activity_getelement_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop action.
        /// </summary>
        public static string activity_getelement_loopaction {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this, once done processing each result, then reruns the selector and looks for new items.
        /// </summary>
        public static string activity_getelement_loopaction_tooltop {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction_tooltop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an browser element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Tab.
        /// </summary>
        public static string activity_gettab {
            get {
                return ResourceManager.GetString("activity_gettab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://OpenRPA.imt-soft.com/en/Native-Messaging#get-tab.
        /// </summary>
        public static string activity_gettab_helpurl {
            get {
                return ResourceManager.GetString("activity_gettab_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current tab in chrome/edge or firefox, return nothing if browser not running.
        /// </summary>
        public static string activity_gettab_tooltip {
            get {
                return ResourceManager.GetString("activity_gettab_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Table Data.
        /// </summary>
        public static string activity_gettable {
            get {
                return ResourceManager.GetString("activity_gettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://OpenRPA.imt-soft.com/en/Native-Messaging#get-table.
        /// </summary>
        public static string activity_gettable_helpurl {
            get {
                return ResourceManager.GetString("activity_gettable_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple table data extraction based on xpaths.
        /// </summary>
        public static string activity_gettable_tooltip {
            get {
                return ResourceManager.GetString("activity_gettable_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Editor.
        /// </summary>
        public static string activity_open_editor {
            get {
                return ResourceManager.GetString("activity_open_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Browser.
        /// </summary>
        public static string activity_openbrowser {
            get {
                return ResourceManager.GetString("activity_openbrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open One Tab.
        /// </summary>
        public static string activity_OpenOneTab {
            get {
                return ResourceManager.GetString("activity_OpenOneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL.
        /// </summary>
        public static string activity_openurl {
            get {
                return ResourceManager.GetString("activity_openurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current.
        /// </summary>
        public static string activity_openurl_getcurrent {
            get {
                return ResourceManager.GetString("activity_openurl_getcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.openiap.io/openrpa.html#openrpa-nm.
        /// </summary>
        public static string activity_openurl_helpurl {
            get {
                return ResourceManager.GetString("activity_openurl_helpurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the specefied url in the selected browser.
        /// </summary>
        public static string activity_openurl_tooltip {
            get {
                return ResourceManager.GetString("activity_openurl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Mode.
        /// </summary>
        public static string activity_ProfileMode {
            get {
                return ResourceManager.GetString("activity_ProfileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Path.
        /// </summary>
        public static string activity_ProfilePath {
            get {
                return ResourceManager.GetString("activity_ProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string activity_selectelement {
            get {
                return ResourceManager.GetString("activity_selectelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Value By.
        /// </summary>
        public static string activity_selectelement_chooseby {
            get {
                return ResourceManager.GetString("activity_selectelement_chooseby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value To Choose.
        /// </summary>
        public static string activity_selectelement_choosevalue {
            get {
                return ResourceManager.GetString("activity_selectelement_choosevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value to choose..
        /// </summary>
        public static string activity_selectelement_choosevalue_hint {
            get {
                return ResourceManager.GetString("activity_selectelement_choosevalue_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch To.
        /// </summary>
        public static string activity_SwitchTo {
            get {
                return ResourceManager.GetString("activity_SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait For Download.
        /// </summary>
        public static string activity_waitfordownload {
            get {
                return ResourceManager.GetString("activity_waitfordownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waits for a download to complete in a nm supported browser.
        /// </summary>
        public static string activity_waitfordownload_tooltip {
            get {
                return ResourceManager.GetString("activity_waitfordownload_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for ready.
        /// </summary>
        public static string activity_waitforready {
            get {
                return ResourceManager.GetString("activity_waitforready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for page page to be ready / is not loading.
        /// </summary>
        public static string activity_waitforready_help {
            get {
                return ResourceManager.GetString("activity_waitforready_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate for old extension.
        /// </summary>
        public static string compensate_for_old_addon {
            get {
                return ResourceManager.GetString("compensate_for_old_addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pixel compensation for old add.
        /// </summary>
        public static string compensate_for_old_addon_help {
            get {
                return ResourceManager.GetString("compensate_for_old_addon_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Console.
        /// </summary>
        public static string debug_console_output {
            get {
                return ResourceManager.GetString("debug_console_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write debug informtation to browser console.
        /// </summary>
        public static string debug_console_output_help {
            get {
                return ResourceManager.GetString("debug_console_output_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect html table.
        /// </summary>
        public static string plugin_detect_html_table {
            get {
                return ResourceManager.GetString("plugin_detect_html_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto add Get Table if clicked on HTML table doing recording.
        /// </summary>
        public static string plugin_detect_html_table_help {
            get {
                return ResourceManager.GetString("plugin_detect_html_table_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait after set value.
        /// </summary>
        public static string plugin_wait_for_tab_after_set_value {
            get {
                return ResourceManager.GetString("plugin_wait_for_tab_after_set_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for tab status to be in ready state after setting a value.
        /// </summary>
        public static string plugin_wait_for_tab_after_set_value_help {
            get {
                return ResourceManager.GetString("plugin_wait_for_tab_after_set_value_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register old portname.
        /// </summary>
        public static string register_old_portname {
            get {
                return ResourceManager.GetString("register_old_portname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register old browser extension port names .
        /// </summary>
        public static string register_old_portname_help {
            get {
                return ResourceManager.GetString("register_old_portname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unique ids.
        /// </summary>
        public static string unique_xpath_ids {
            get {
                return ResourceManager.GetString("unique_xpath_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use on of these attributes as unique id&apos;s when creating xpath selectors.
        /// </summary>
        public static string unique_xpath_ids_help {
            get {
                return ResourceManager.GetString("unique_xpath_ids_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait for tab.
        /// </summary>
        public static string wait_for_tab_click {
            get {
                return ResourceManager.GetString("wait_for_tab_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for tab status to be in ready state after clicking a button.
        /// </summary>
        public static string wait_for_tab_click_help {
            get {
                return ResourceManager.GetString("wait_for_tab_click_help", resourceCulture);
            }
        }
    }
}
