//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Forms.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert message.
        /// </summary>
        public static string activity_alert_message_hint {
            get {
                return ResourceManager.GetString("activity_alert_message_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build form.
        /// </summary>
        public static string activity_formdesigner_build {
            get {
                return ResourceManager.GetString("activity_formdesigner_build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Formula.
        /// </summary>
        public static string activity_invokeform {
            get {
                return ResourceManager.GetString("activity_invokeform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create variables.
        /// </summary>
        public static string activity_invokeform_create_var {
            get {
                return ResourceManager.GetString("activity_invokeform_create_var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open designer.
        /// </summary>
        public static string activity_invokeform_open {
            get {
                return ResourceManager.GetString("activity_invokeform_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do interaction with user at the computer with predesigned formulas.
        /// </summary>
        public static string activity_invokeform_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeform_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map variables.
        /// </summary>
        public static string activity_map_variables {
            get {
                return ResourceManager.GetString("activity_map_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string activity_noti_message {
            get {
                return ResourceManager.GetString("activity_noti_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification message.
        /// </summary>
        public static string activity_noti_message_hint {
            get {
                return ResourceManager.GetString("activity_noti_message_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification.
        /// </summary>
        public static string activity_shownotification {
            get {
                return ResourceManager.GetString("activity_shownotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification in the lower right corner of the screen for a limited amount of time.
        /// </summary>
        public static string activity_shownotification_tooltip {
            get {
                return ResourceManager.GetString("activity_shownotification_tooltip", resourceCulture);
            }
        }
    }
}
