//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.PMPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.PMPlugin.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collectionname.
        /// </summary>
        public static string plugin_collectionname {
            get {
                return ResourceManager.GetString("plugin_collectionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save events to this collection.
        /// </summary>
        public static string plugin_collectionname_help {
            get {
                return ResourceManager.GetString("plugin_collectionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture keyboard.
        /// </summary>
        public static string plugin_enabled_keyboard_recording {
            get {
                return ResourceManager.GetString("plugin_enabled_keyboard_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record all keyboard events.
        /// </summary>
        public static string plugin_enabled_keyboard_recording_help {
            get {
                return ResourceManager.GetString("plugin_enabled_keyboard_recording_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture mouse.
        /// </summary>
        public static string plugin_enabled_mouse_recording {
            get {
                return ResourceManager.GetString("plugin_enabled_mouse_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record all mouse clicks.
        /// </summary>
        public static string plugin_enabled_mouse_recording_help {
            get {
                return ResourceManager.GetString("plugin_enabled_mouse_recording_help", resourceCulture);
            }
        }
    }
}
