//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.IE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.IE.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an Windows UI element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL.
        /// </summary>
        public static string activity_openurl {
            get {
                return ResourceManager.GetString("activity_openurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get current.
        /// </summary>
        public static string activity_openurl_getcurrent {
            get {
                return ResourceManager.GetString("activity_openurl_getcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the specefied url in Internet Explorer.
        /// </summary>
        public static string activity_openurl_tooltip {
            get {
                return ResourceManager.GetString("activity_openurl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for ready.
        /// </summary>
        public static string activity_waitforready {
            get {
                return ResourceManager.GetString("activity_waitforready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for page page to be ready / is not loading.
        /// </summary>
        public static string activity_waitforready_help {
            get {
                return ResourceManager.GetString("activity_waitforready_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching browser object.
        /// </summary>
        public static string enable_caching_browser {
            get {
                return ResourceManager.GetString("enable_caching_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save browser object, instead of searching for the window doing each call.
        /// </summary>
        public static string enable_caching_browser_help {
            get {
                return ResourceManager.GetString("enable_caching_browser_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XPath.
        /// </summary>
        public static string enable_xpath_support {
            get {
                return ResourceManager.GetString("enable_xpath_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable experimental XPath support in IE.
        /// </summary>
        public static string enable_xpath_support_help {
            get {
                return ResourceManager.GetString("enable_xpath_support_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open browser timeout.
        /// </summary>
        public static string open_browser_timeout {
            get {
                return ResourceManager.GetString("open_browser_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout on opening browser and opening an url.
        /// </summary>
        public static string open_browser_timeout_help {
            get {
                return ResourceManager.GetString("open_browser_timeout_help", resourceCulture);
            }
        }
    }
}
