//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Office.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Office.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Paragraph.
        /// </summary>
        public static string activity_addparagraph {
            get {
                return ResourceManager.GetString("activity_addparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_addparagraph_filename {
            get {
                return ResourceManager.GetString("activity_addparagraph_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path and filename of Microsoft Word document to work with.
        /// </summary>
        public static string activity_addparagraph_filename_help {
            get {
                return ResourceManager.GetString("activity_addparagraph_filename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string activity_addparagraph_index {
            get {
                return ResourceManager.GetString("activity_addparagraph_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the new paragraph at this index (zero indexed) Leave blank to add at the end of the document.
        /// </summary>
        public static string activity_addparagraph_index_help {
            get {
                return ResourceManager.GetString("activity_addparagraph_index_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_addparagraph_text {
            get {
                return ResourceManager.GetString("activity_addparagraph_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to add.
        /// </summary>
        public static string activity_addparagraph_text_help {
            get {
                return ResourceManager.GetString("activity_addparagraph_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Paragraph to a Microsoft Word document.
        /// </summary>
        public static string activity_addparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_addparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Range.
        /// </summary>
        public static string activity_clearrange {
            get {
                return ResourceManager.GetString("activity_clearrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string activity_clearrange_cells {
            get {
                return ResourceManager.GetString("activity_clearrange_cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set what cells to clear, leave blank to clear all cells.
        /// </summary>
        public static string activity_clearrange_cells_help {
            get {
                return ResourceManager.GetString("activity_clearrange_cells_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all data and formating from a range of cells.
        /// </summary>
        public static string activity_clearrange_tooltip {
            get {
                return ResourceManager.GetString("activity_clearrange_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Document.
        /// </summary>
        public static string activity_closedocument {
            get {
                return ResourceManager.GetString("activity_closedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_closedocument_filename {
            get {
                return ResourceManager.GetString("activity_closedocument_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path and filename of Microsoft Word document to work with.
        /// </summary>
        public static string activity_closedocument_filename_help {
            get {
                return ResourceManager.GetString("activity_closedocument_filename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string activity_closedocument_savechanges {
            get {
                return ResourceManager.GetString("activity_closedocument_savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to true, to save the word file, set to false to discard any changces made.
        /// </summary>
        public static string activity_closedocument_savechanges_help {
            get {
                return ResourceManager.GetString("activity_closedocument_savechanges_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close a Microsoft Word document if open, will also closes word if no more documents are open.
        /// </summary>
        public static string activity_closedocument_tooltip {
            get {
                return ResourceManager.GetString("activity_closedocument_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workbook.
        /// </summary>
        public static string activity_closeworkbook {
            get {
                return ResourceManager.GetString("activity_closeworkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_closeworkbook_filename {
            get {
                return ResourceManager.GetString("activity_closeworkbook_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path and filename of Microsoft Excel workbook to work with.
        /// </summary>
        public static string activity_closeworkbook_filename_help {
            get {
                return ResourceManager.GetString("activity_closeworkbook_filename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string activity_closeworkbook_savechanges {
            get {
                return ResourceManager.GetString("activity_closeworkbook_savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to true, to save the excel file, set to false to discard any changces made.
        /// </summary>
        public static string activity_closeworkbook_savechanges_help {
            get {
                return ResourceManager.GetString("activity_closeworkbook_savechanges_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close a Workbook if open, will also closes excel if no more workbooks are open.
        /// </summary>
        public static string activity_closeworkbook_tooltip {
            get {
                return ResourceManager.GetString("activity_closeworkbook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbook.
        /// </summary>
        public static string activity_closeworkbook_workbook {
            get {
                return ResourceManager.GetString("activity_closeworkbook_workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Microsoft Excel workbook variable to work with.
        /// </summary>
        public static string activity_closeworkbook_workbook_help {
            get {
                return ResourceManager.GetString("activity_closeworkbook_workbook_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Workbook.
        /// </summary>
        public static string activity_ExportWorkbook {
            get {
                return ResourceManager.GetString("activity_ExportWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current open workbook as an pdf or xps format.
        /// </summary>
        public static string activity_ExportWorkbook_tooltip {
            get {
                return ResourceManager.GetString("activity_ExportWorkbook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_filename {
            get {
                return ResourceManager.GetString("activity_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string activity_getemails_reload {
            get {
                return ResourceManager.GetString("activity_getemails_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Mails.
        /// </summary>
        public static string activity_getmails {
            get {
                return ResourceManager.GetString("activity_getmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string activity_getmails_filter {
            get {
                return ResourceManager.GetString("activity_getmails_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter emails by query.
        /// </summary>
        public static string activity_getmails_filter_hint {
            get {
                return ResourceManager.GetString("activity_getmails_filter_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all emails from a Microsoft Outlook folder.
        /// </summary>
        public static string activity_getmails_tooltip {
            get {
                return ResourceManager.GetString("activity_getmails_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Paragraph.
        /// </summary>
        public static string activity_getparagraph {
            get {
                return ResourceManager.GetString("activity_getparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string activity_getparagraph_count {
            get {
                return ResourceManager.GetString("activity_getparagraph_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of paragraphs in the Microsoft Word document.
        /// </summary>
        public static string activity_getparagraph_count_help {
            get {
                return ResourceManager.GetString("activity_getparagraph_count_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_getparagraph_filename {
            get {
                return ResourceManager.GetString("activity_getparagraph_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path and filename of Microsoft Word document to work with.
        /// </summary>
        public static string activity_getparagraph_filename_help {
            get {
                return ResourceManager.GetString("activity_getparagraph_filename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string activity_getparagraph_index {
            get {
                return ResourceManager.GetString("activity_getparagraph_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the content of the paragraph with this index and a MaxResults more. Leave this field blank to get the entire word document.
        /// </summary>
        public static string activity_getparagraph_index_help {
            get {
                return ResourceManager.GetString("activity_getparagraph_index_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results.
        /// </summary>
        public static string activity_getparagraph_maxresults {
            get {
                return ResourceManager.GetString("activity_getparagraph_maxresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the amount of paragraphs to get, leave blank or at 0 to get all from Index and onward.
        /// </summary>
        public static string activity_getparagraph_maxresults_help {
            get {
                return ResourceManager.GetString("activity_getparagraph_maxresults_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_getparagraph_text {
            get {
                return ResourceManager.GetString("activity_getparagraph_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the read paragrahs to this variable.
        /// </summary>
        public static string activity_getparagraph_text_help {
            get {
                return ResourceManager.GetString("activity_getparagraph_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get one or more paragraphs from a Microsoft Word document.
        /// </summary>
        public static string activity_getparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_getparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Selected Range.
        /// </summary>
        public static string activity_getselectedrange {
            get {
                return ResourceManager.GetString("activity_getselectedrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the currently selected cells in the specefied worksheet.
        /// </summary>
        public static string activity_getselectedrange_tooltip {
            get {
                return ResourceManager.GetString("activity_getselectedrange_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string activity_movemail_mail {
            get {
                return ResourceManager.GetString("activity_movemail_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail item to move.
        /// </summary>
        public static string activity_movemail_mail_hint {
            get {
                return ResourceManager.GetString("activity_movemail_mail_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move MailItem.
        /// </summary>
        public static string activity_movemailitem {
            get {
                return ResourceManager.GetString("activity_movemailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move a mail gotten with GetEmails to a different folder.
        /// </summary>
        public static string activity_movemailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_movemailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MailItem.
        /// </summary>
        public static string activity_newmailitem {
            get {
                return ResourceManager.GetString("activity_newmailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Microsoft Outlook Mailitem.
        /// </summary>
        public static string activity_newmailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_newmailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string activity_password {
            get {
                return ResourceManager.GetString("activity_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Worksheet.
        /// </summary>
        public static string activity_protectworksheet {
            get {
                return ResourceManager.GetString("activity_protectworksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect current worksheet from changes.
        /// </summary>
        public static string activity_protectworksheet_tooltip {
            get {
                return ResourceManager.GetString("activity_protectworksheet_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Cell.
        /// </summary>
        public static string activity_readcell {
            get {
                return ResourceManager.GetString("activity_readcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the content of a single cell in Microsoft Excel.
        /// </summary>
        public static string activity_readcell_tooltip {
            get {
                return ResourceManager.GetString("activity_readcell_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Range.
        /// </summary>
        public static string activity_readrange {
            get {
                return ResourceManager.GetString("activity_readrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Formats.
        /// </summary>
        public static string activity_readrange_clearformats {
            get {
                return ResourceManager.GetString("activity_readrange_clearformats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to true to remove all formatting from the select worksheet.
        /// </summary>
        public static string activity_readrange_clearformats_help {
            get {
                return ResourceManager.GetString("activity_readrange_clearformats_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read a range from a Microsoft Excel sheet.
        /// </summary>
        public static string activity_readrange_tooltip {
            get {
                return ResourceManager.GetString("activity_readrange_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Header Row.
        /// </summary>
        public static string activity_readrange_useheaderrow {
            get {
                return ResourceManager.GetString("activity_readrange_useheaderrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If select range also contains a header row with column names, set this to true, else leave blank ( then all cloumns will have no name ).
        /// </summary>
        public static string activity_readrange_useheaderrow_help {
            get {
                return ResourceManager.GetString("activity_readrange_useheaderrow_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply MailItem.
        /// </summary>
        public static string activity_replymailitem {
            get {
                return ResourceManager.GetString("activity_replymailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a reply to a Microsoft Outlook Mailitem.
        /// </summary>
        public static string activity_replymailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_replymailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Excel Macro.
        /// </summary>
        public static string activity_runexcelmacro {
            get {
                return ResourceManager.GetString("activity_runexcelmacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Name.
        /// </summary>
        public static string activity_runexcelmacro_name_hint {
            get {
                return ResourceManager.GetString("activity_runexcelmacro_name_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a Macro within a Excel workbook. The Workbook file needs to be enabled for Macros.
        /// </summary>
        public static string activity_runexcelmacro_tooltip {
            get {
                return ResourceManager.GetString("activity_runexcelmacro_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Slideshow.
        /// </summary>
        public static string activity_runslideshow {
            get {
                return ResourceManager.GetString("activity_runslideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Microsoft Powerpoint Presentation and start slide show.
        /// </summary>
        public static string activity_runslideshow_tooltip {
            get {
                return ResourceManager.GetString("activity_runslideshow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save MailItem.
        /// </summary>
        public static string activity_savemailitem {
            get {
                return ResourceManager.GetString("activity_savemailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Microsoft Outlook Mail item as a file.
        /// </summary>
        public static string activity_savemailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_savemailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Paragraph.
        /// </summary>
        public static string activity_setparagraph {
            get {
                return ResourceManager.GetString("activity_setparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_setparagraph_filename {
            get {
                return ResourceManager.GetString("activity_setparagraph_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path and filename of Microsoft Word document to work with.
        /// </summary>
        public static string activity_setparagraph_filename_help {
            get {
                return ResourceManager.GetString("activity_setparagraph_filename_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string activity_setparagraph_index {
            get {
                return ResourceManager.GetString("activity_setparagraph_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite content in the paragraph with this index, set 0 to overwrite the entire word document.
        /// </summary>
        public static string activity_setparagraph_index_help {
            get {
                return ResourceManager.GetString("activity_setparagraph_index_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_setparagraph_text {
            get {
                return ResourceManager.GetString("activity_setparagraph_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to set.
        /// </summary>
        public static string activity_setparagraph_text_help {
            get {
                return ResourceManager.GetString("activity_setparagraph_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set content of a paragraph in side a Microsoft Word document.
        /// </summary>
        public static string activity_setparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_setparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprotect Worksheet.
        /// </summary>
        public static string activity_unprotectworksheet {
            get {
                return ResourceManager.GetString("activity_unprotectworksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the protection of current worksheet.
        /// </summary>
        public static string activity_unprotectworksheet_tooltip {
            get {
                return ResourceManager.GetString("activity_unprotectworksheet_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Cell.
        /// </summary>
        public static string activity_writecell {
            get {
                return ResourceManager.GetString("activity_writecell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a value or formular to a single cell in Microsoft Excel.
        /// </summary>
        public static string activity_writecell_tooltip {
            get {
                return ResourceManager.GetString("activity_writecell_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Range.
        /// </summary>
        public static string activity_writerange {
            get {
                return ResourceManager.GetString("activity_writerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string activity_writerange_cells {
            get {
                return ResourceManager.GetString("activity_writerange_cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the first cell to start writing from, leave blank to start at last empty row in column A.
        /// </summary>
        public static string activity_writerange_cells_help {
            get {
                return ResourceManager.GetString("activity_writerange_cells_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string activity_writerange_datatable {
            get {
                return ResourceManager.GetString("activity_writerange_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The datatable containing the data to add to Excel.
        /// </summary>
        public static string activity_writerange_datatable_help {
            get {
                return ResourceManager.GetString("activity_writerange_datatable_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write all data from a DataTable to at a range inside a Microsoft Excel sheet.
        /// </summary>
        public static string activity_writerange_tooltip {
            get {
                return ResourceManager.GetString("activity_writerange_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Header Row.
        /// </summary>
        public static string activity_writerange_useheaderrow {
            get {
                return ResourceManager.GetString("activity_writerange_useheaderrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set to true, will also add a header row with column names as the first row, set to false to only add the data.
        /// </summary>
        public static string activity_writerange_useheaderrow_help {
            get {
                return ResourceManager.GetString("activity_writerange_useheaderrow_help", resourceCulture);
            }
        }
    }
}
