//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Office.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Office.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Paragraph.
        /// </summary>
        public static string activity_addparagraph {
            get {
                return ResourceManager.GetString("activity_addparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Paragraph to a Microsoft Word document.
        /// </summary>
        public static string activity_addparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_addparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Document.
        /// </summary>
        public static string activity_closedocument {
            get {
                return ResourceManager.GetString("activity_closedocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close a Microsoft Word document if open, will also closes word if no more documents are open.
        /// </summary>
        public static string activity_closedocument_tooltip {
            get {
                return ResourceManager.GetString("activity_closedocument_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workbook.
        /// </summary>
        public static string activity_closeworkbook {
            get {
                return ResourceManager.GetString("activity_closeworkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close a Workbook if open, will also closes excel if no more workbooks are open.
        /// </summary>
        public static string activity_closeworkbook_tooltip {
            get {
                return ResourceManager.GetString("activity_closeworkbook_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_filename {
            get {
                return ResourceManager.GetString("activity_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Mails.
        /// </summary>
        public static string activity_getmails {
            get {
                return ResourceManager.GetString("activity_getmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all emails from a Microsoft Outlook folder.
        /// </summary>
        public static string activity_getmails_tooltip {
            get {
                return ResourceManager.GetString("activity_getmails_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Paragraph.
        /// </summary>
        public static string activity_getparagraph {
            get {
                return ResourceManager.GetString("activity_getparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get one or more paragraphs from a Microsoft Word document.
        /// </summary>
        public static string activity_getparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_getparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New MailItem.
        /// </summary>
        public static string activity_newmailitem {
            get {
                return ResourceManager.GetString("activity_newmailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Microsoft Outlook Mailitem.
        /// </summary>
        public static string activity_newmailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_newmailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Cell.
        /// </summary>
        public static string activity_readcell {
            get {
                return ResourceManager.GetString("activity_readcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the content of a single cell in Microsoft Excel.
        /// </summary>
        public static string activity_readcell_tooltip {
            get {
                return ResourceManager.GetString("activity_readcell_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Range.
        /// </summary>
        public static string activity_readrange {
            get {
                return ResourceManager.GetString("activity_readrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read a range from a Microsoft Excel sheet.
        /// </summary>
        public static string activity_readrange_tooltip {
            get {
                return ResourceManager.GetString("activity_readrange_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Slideshow.
        /// </summary>
        public static string activity_runslideshow {
            get {
                return ResourceManager.GetString("activity_runslideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Microsoft Powerpoint Presentation and start slide show.
        /// </summary>
        public static string activity_runslideshow_tooltip {
            get {
                return ResourceManager.GetString("activity_runslideshow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save MailItem.
        /// </summary>
        public static string activity_savemailitem {
            get {
                return ResourceManager.GetString("activity_savemailitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Microsoft Outlook Mail item as a file.
        /// </summary>
        public static string activity_savemailitem_tooltip {
            get {
                return ResourceManager.GetString("activity_savemailitem_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Paragraph.
        /// </summary>
        public static string activity_setparagraph {
            get {
                return ResourceManager.GetString("activity_setparagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set content of a paragraph in side a Microsoft Word document.
        /// </summary>
        public static string activity_setparagraph_tooltip {
            get {
                return ResourceManager.GetString("activity_setparagraph_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Cell.
        /// </summary>
        public static string activity_writecell {
            get {
                return ResourceManager.GetString("activity_writecell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a value or formular to a single cell in Microsoft Excel.
        /// </summary>
        public static string activity_writecell_tooltip {
            get {
                return ResourceManager.GetString("activity_writecell_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Range.
        /// </summary>
        public static string activity_writerange {
            get {
                return ResourceManager.GetString("activity_writerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write all data from a DataTable to at a range inside a Microsoft Excel sheet.
        /// </summary>
        public static string activity_writerange_tooltip {
            get {
                return ResourceManager.GetString("activity_writerange_tooltip", resourceCulture);
            }
        }
    }
}
