//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.SAP.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.SAP.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displayname.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute transaction.
        /// </summary>
        public static string activity_executetransaction {
            get {
                return ResourceManager.GetString("activity_executetransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path.
        /// </summary>
        public static string activity_executetransaction_path {
            get {
                return ResourceManager.GetString("activity_executetransaction_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path to object [SAP id to se(ssion). eg.: &quot;/app/con[0]/ses[0]&quot;].
        /// </summary>
        public static string activity_executetransaction_path_help {
            get {
                return ResourceManager.GetString("activity_executetransaction_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name.
        /// </summary>
        public static string activity_executetransaction_systemname {
            get {
                return ResourceManager.GetString("activity_executetransaction_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System name.
        /// </summary>
        public static string activity_executetransaction_systemname_help {
            get {
                return ResourceManager.GetString("activity_executetransaction_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute SAP transaction.
        /// </summary>
        public static string activity_executetransaction_tooltip {
            get {
                return ResourceManager.GetString("activity_executetransaction_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction code.
        /// </summary>
        public static string activity_executetransaction_transactioncode {
            get {
                return ResourceManager.GetString("activity_executetransaction_transactioncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of the transaction to eecute.
        /// </summary>
        public static string activity_executetransaction_transactioncode_help {
            get {
                return ResourceManager.GetString("activity_executetransaction_transactioncode_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find an SAP element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Property.
        /// </summary>
        public static string activity_getproperty {
            get {
                return ResourceManager.GetString("activity_getproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property Name.
        /// </summary>
        public static string activity_getproperty_actionname {
            get {
                return ResourceManager.GetString("activity_getproperty_actionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of property to Get.
        /// </summary>
        public static string activity_getproperty_actionname_help {
            get {
                return ResourceManager.GetString("activity_getproperty_actionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path.
        /// </summary>
        public static string activity_getproperty_path {
            get {
                return ResourceManager.GetString("activity_getproperty_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path to object.
        /// </summary>
        public static string activity_getproperty_path_help {
            get {
                return ResourceManager.GetString("activity_getproperty_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        public static string activity_getproperty_result {
            get {
                return ResourceManager.GetString("activity_getproperty_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The result from getting the Property.
        /// </summary>
        public static string activity_getproperty_result_help {
            get {
                return ResourceManager.GetString("activity_getproperty_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name.
        /// </summary>
        public static string activity_getproperty_systemname {
            get {
                return ResourceManager.GetString("activity_getproperty_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name to send command to.
        /// </summary>
        public static string activity_getproperty_systemname_help {
            get {
                return ResourceManager.GetString("activity_getproperty_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get SAP UI Element property value.
        /// </summary>
        public static string activity_getproperty_tooltip {
            get {
                return ResourceManager.GetString("activity_getproperty_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoke Method.
        /// </summary>
        public static string activity_invokemethod {
            get {
                return ResourceManager.GetString("activity_invokemethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action Name.
        /// </summary>
        public static string activity_invokemethod_actionname {
            get {
                return ResourceManager.GetString("activity_invokemethod_actionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action to perform on object.
        /// </summary>
        public static string activity_invokemethod_actionname_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_actionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters.
        /// </summary>
        public static string activity_invokemethod_parameters {
            get {
                return ResourceManager.GetString("activity_invokemethod_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patameters for Action.
        /// </summary>
        public static string activity_invokemethod_parameters_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_parameters_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path.
        /// </summary>
        public static string activity_invokemethod_path {
            get {
                return ResourceManager.GetString("activity_invokemethod_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path to object.
        /// </summary>
        public static string activity_invokemethod_path_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        public static string activity_invokemethod_result {
            get {
                return ResourceManager.GetString("activity_invokemethod_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The return value from Invoke Method if it has one.
        /// </summary>
        public static string activity_invokemethod_result_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name.
        /// </summary>
        public static string activity_invokemethod_systemname {
            get {
                return ResourceManager.GetString("activity_invokemethod_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name to send command to.
        /// </summary>
        public static string activity_invokemethod_systemname_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invoke SAP UI Method.
        /// </summary>
        public static string activity_invokemethod_tooltip {
            get {
                return ResourceManager.GetString("activity_invokemethod_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string activity_login {
            get {
                return ResourceManager.GetString("activity_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        public static string activity_login_client {
            get {
                return ResourceManager.GetString("activity_login_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAP Client to use.
        /// </summary>
        public static string activity_login_client_help {
            get {
                return ResourceManager.GetString("activity_login_client_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string activity_login_host {
            get {
                return ResourceManager.GetString("activity_login_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server IP or hostname.
        /// </summary>
        public static string activity_login_host_help {
            get {
                return ResourceManager.GetString("activity_login_host_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string activity_login_language {
            get {
                return ResourceManager.GetString("activity_login_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Language of client.
        /// </summary>
        public static string activity_login_language_help {
            get {
                return ResourceManager.GetString("activity_login_language_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string activity_login_password {
            get {
                return ResourceManager.GetString("activity_login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password for user to login with.
        /// </summary>
        public static string activity_login_password_help {
            get {
                return ResourceManager.GetString("activity_login_password_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name.
        /// </summary>
        public static string activity_login_systemname {
            get {
                return ResourceManager.GetString("activity_login_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expected System Name, will search for a session to this system, and only login if non is found. Leave empty to always login to a new session.
        /// </summary>
        public static string activity_login_systemname_help {
            get {
                return ResourceManager.GetString("activity_login_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login to sap using the credentials, unless a session with the given name exists.
        /// </summary>
        public static string activity_login_tooltip {
            get {
                return ResourceManager.GetString("activity_login_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string activity_login_username {
            get {
                return ResourceManager.GetString("activity_login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username to login with.
        /// </summary>
        public static string activity_login_username_help {
            get {
                return ResourceManager.GetString("activity_login_username_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Map variables.
        /// </summary>
        public static string activity_map_variables {
            get {
                return ResourceManager.GetString("activity_map_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Property.
        /// </summary>
        public static string activity_setproperty {
            get {
                return ResourceManager.GetString("activity_setproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property Name.
        /// </summary>
        public static string activity_setproperty_actionname {
            get {
                return ResourceManager.GetString("activity_setproperty_actionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of property to Set.
        /// </summary>
        public static string activity_setproperty_actionname_help {
            get {
                return ResourceManager.GetString("activity_setproperty_actionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameters.
        /// </summary>
        public static string activity_setproperty_parameters {
            get {
                return ResourceManager.GetString("activity_setproperty_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patameters for Action.
        /// </summary>
        public static string activity_setproperty_parameters_help {
            get {
                return ResourceManager.GetString("activity_setproperty_parameters_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path.
        /// </summary>
        public static string activity_setproperty_path {
            get {
                return ResourceManager.GetString("activity_setproperty_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Path to object.
        /// </summary>
        public static string activity_setproperty_path_help {
            get {
                return ResourceManager.GetString("activity_setproperty_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name.
        /// </summary>
        public static string activity_setproperty_systemname {
            get {
                return ResourceManager.GetString("activity_setproperty_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Name to send command to.
        /// </summary>
        public static string activity_setproperty_systemname_help {
            get {
                return ResourceManager.GetString("activity_setproperty_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set the property value of an SAP UI Element.
        /// </summary>
        public static string activity_setproperty_tooltip {
            get {
                return ResourceManager.GetString("activity_setproperty_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto launch.
        /// </summary>
        public static string plugin_auto_launch_sap_bridge {
            get {
                return ResourceManager.GetString("plugin_auto_launch_sap_bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto launch SAP bridge when robot is running.
        /// </summary>
        public static string plugin_auto_launch_sap_bridge_help {
            get {
                return ResourceManager.GetString("plugin_auto_launch_sap_bridge_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bridge Timeout.
        /// </summary>
        public static string plugin_bridge_timeout_seconds {
            get {
                return ResourceManager.GetString("plugin_bridge_timeout_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How long to wait per request to SAP bridge.
        /// </summary>
        public static string plugin_bridge_timeout_seconds_help {
            get {
                return ResourceManager.GetString("plugin_bridge_timeout_seconds_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch SAP bridge.
        /// </summary>
        public static string plugin_launch_sap_bridge {
            get {
                return ResourceManager.GetString("plugin_launch_sap_bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record Get Element.
        /// </summary>
        public static string plugin_record_with_get_element {
            get {
                return ResourceManager.GetString("plugin_record_with_get_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doing recording use GetElement instead of SetProperty.
        /// </summary>
        public static string plugin_record_with_get_element_help {
            get {
                return ResourceManager.GetString("plugin_record_with_get_element_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip methods.
        /// </summary>
        public static string plugin_recording_skip_methods {
            get {
                return ResourceManager.GetString("plugin_recording_skip_methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doing recording skip adding these methods.
        /// </summary>
        public static string plugin_recording_skip_methods_help {
            get {
                return ResourceManager.GetString("plugin_recording_skip_methods_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skip properties.
        /// </summary>
        public static string plugin_recording_skip_properties {
            get {
                return ResourceManager.GetString("plugin_recording_skip_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doing recording the value of these properties.
        /// </summary>
        public static string plugin_recording_skip_properties_help {
            get {
                return ResourceManager.GetString("plugin_recording_skip_properties_help", resourceCulture);
            }
        }
    }
}
