//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.SAP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.SAP.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an SAP element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Method.
        /// </summary>
        public static string activity_invokemethod {
            get {
                return ResourceManager.GetString("activity_invokemethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string activity_invokemethod_actionname {
            get {
                return ResourceManager.GetString("activity_invokemethod_actionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to perform on object.
        /// </summary>
        public static string activity_invokemethod_actionname_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_actionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string activity_invokemethod_parameters {
            get {
                return ResourceManager.GetString("activity_invokemethod_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patameters for Action.
        /// </summary>
        public static string activity_invokemethod_parameters_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_parameters_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string activity_invokemethod_path {
            get {
                return ResourceManager.GetString("activity_invokemethod_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to object.
        /// </summary>
        public static string activity_invokemethod_path_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string activity_invokemethod_systemname {
            get {
                return ResourceManager.GetString("activity_invokemethod_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name to send command to.
        /// </summary>
        public static string activity_invokemethod_systemname_help {
            get {
                return ResourceManager.GetString("activity_invokemethod_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke SAP UI Method.
        /// </summary>
        public static string activity_invokemethod_tooltip {
            get {
                return ResourceManager.GetString("activity_invokemethod_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string activity_login {
            get {
                return ResourceManager.GetString("activity_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string activity_login_client {
            get {
                return ResourceManager.GetString("activity_login_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP Client to use.
        /// </summary>
        public static string activity_login_client_help {
            get {
                return ResourceManager.GetString("activity_login_client_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string activity_login_host {
            get {
                return ResourceManager.GetString("activity_login_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP or hostname.
        /// </summary>
        public static string activity_login_host_help {
            get {
                return ResourceManager.GetString("activity_login_host_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string activity_login_language {
            get {
                return ResourceManager.GetString("activity_login_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language of client.
        /// </summary>
        public static string activity_login_language_help {
            get {
                return ResourceManager.GetString("activity_login_language_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string activity_login_password {
            get {
                return ResourceManager.GetString("activity_login_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for user to login with.
        /// </summary>
        public static string activity_login_password_help {
            get {
                return ResourceManager.GetString("activity_login_password_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string activity_login_systemname {
            get {
                return ResourceManager.GetString("activity_login_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected System Name, will search for a session to this system, and only login if non is found. Leave empty to always login to a new session.
        /// </summary>
        public static string activity_login_systemname_help {
            get {
                return ResourceManager.GetString("activity_login_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to sap using the credentials, unless a session with the given name exists.
        /// </summary>
        public static string activity_login_tooltip {
            get {
                return ResourceManager.GetString("activity_login_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string activity_login_username {
            get {
                return ResourceManager.GetString("activity_login_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username to login with.
        /// </summary>
        public static string activity_login_username_help {
            get {
                return ResourceManager.GetString("activity_login_username_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map variables.
        /// </summary>
        public static string activity_map_variables {
            get {
                return ResourceManager.GetString("activity_map_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Property.
        /// </summary>
        public static string activity_setproperty {
            get {
                return ResourceManager.GetString("activity_setproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string activity_setproperty_actionname {
            get {
                return ResourceManager.GetString("activity_setproperty_actionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to perform on object.
        /// </summary>
        public static string activity_setproperty_actionname_help {
            get {
                return ResourceManager.GetString("activity_setproperty_actionname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string activity_setproperty_parameters {
            get {
                return ResourceManager.GetString("activity_setproperty_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patameters for Action.
        /// </summary>
        public static string activity_setproperty_parameters_help {
            get {
                return ResourceManager.GetString("activity_setproperty_parameters_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string activity_setproperty_path {
            get {
                return ResourceManager.GetString("activity_setproperty_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to object.
        /// </summary>
        public static string activity_setproperty_path_help {
            get {
                return ResourceManager.GetString("activity_setproperty_path_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name to send command to.
        /// </summary>
        public static string activity_setproperty_systemname {
            get {
                return ResourceManager.GetString("activity_setproperty_systemname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string activity_setproperty_systemname_help {
            get {
                return ResourceManager.GetString("activity_setproperty_systemname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the property value of an SAP UI Element.
        /// </summary>
        public static string activity_setproperty_tooltip {
            get {
                return ResourceManager.GetString("activity_setproperty_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto launch.
        /// </summary>
        public static string plugin_auto_launch_sap_bridge {
            get {
                return ResourceManager.GetString("plugin_auto_launch_sap_bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto launch SAP bridge when robot is running.
        /// </summary>
        public static string plugin_auto_launch_sap_bridge_help {
            get {
                return ResourceManager.GetString("plugin_auto_launch_sap_bridge_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch SAP bridge.
        /// </summary>
        public static string plugin_launch_sap_bridge {
            get {
                return ResourceManager.GetString("plugin_launch_sap_bridge", resourceCulture);
            }
        }
    }
}
