//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Interfaces.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Interfaces.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string selector_buttons_cancel {
            get {
                return ResourceManager.GetString("selector_buttons_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes and close selector window.
        /// </summary>
        public static string selector_buttons_cancel_hint {
            get {
                return ResourceManager.GetString("selector_buttons_cancel_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string selector_buttons_highlight {
            get {
                return ResourceManager.GetString("selector_buttons_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highligt element(s) effected by current selector.
        /// </summary>
        public static string selector_buttons_highlight_hint {
            get {
                return ResourceManager.GetString("selector_buttons_highlight_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string selector_buttons_ok {
            get {
                return ResourceManager.GetString("selector_buttons_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept changes and close selector window.
        /// </summary>
        public static string selector_buttons_ok_hint {
            get {
                return ResourceManager.GetString("selector_buttons_ok_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string selector_buttons_select {
            get {
                return ResourceManager.GetString("selector_buttons_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select element by clicking it.
        /// </summary>
        public static string selector_buttons_select_hint {
            get {
                return ResourceManager.GetString("selector_buttons_select_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync tree.
        /// </summary>
        public static string selector_buttons_sync {
            get {
                return ResourceManager.GetString("selector_buttons_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync tree and go to current element.
        /// </summary>
        public static string selector_buttons_sync_hint {
            get {
                return ResourceManager.GetString("selector_buttons_sync_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string selector_menu_select {
            get {
                return ResourceManager.GetString("selector_menu_select", resourceCulture);
            }
        }
    }
}
