//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Utilities.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable to insert into.
        /// </summary>
        public static string activity_adddatarow_datatable {
            get {
                return ResourceManager.GetString("activity_adddatarow_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save zip file with this filename.
        /// </summary>
        public static string activity_compressarchive_filename_hint {
            get {
                return ResourceManager.GetString("activity_compressarchive_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all files from this folder.
        /// </summary>
        public static string activity_compressarchive_path_hint {
            get {
                return ResourceManager.GetString("activity_compressarchive_path_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datatable.
        /// </summary>
        public static string activity_converter_datatable {
            get {
                return ResourceManager.GetString("activity_converter_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JArray.
        /// </summary>
        public static string activity_converter_jarray {
            get {
                return ResourceManager.GetString("activity_converter_jarray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string activity_datatable {
            get {
                return ResourceManager.GetString("activity_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array of DataTable columns.
        /// </summary>
        public static string activity_datatable_columnnames {
            get {
                return ResourceManager.GetString("activity_datatable_columnnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New columns Name.
        /// </summary>
        public static string activity_datatable_newcolumnname {
            get {
                return ResourceManager.GetString("activity_datatable_newcolumnname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string activity_deletedatarow_row {
            get {
                return ResourceManager.GetString("activity_deletedatarow_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save into this folder.
        /// </summary>
        public static string activity_downloadfile_hint {
            get {
                return ResourceManager.GetString("activity_downloadfile_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ZIP file to expand.
        /// </summary>
        public static string activity_expandarchive_filename_hint {
            get {
                return ResourceManager.GetString("activity_expandarchive_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination folder.
        /// </summary>
        public static string activity_expandarchive_path_hint {
            get {
                return ResourceManager.GetString("activity_expandarchive_path_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiled.
        /// </summary>
        public static string activity_match_compiled {
            get {
                return ResourceManager.GetString("activity_match_compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string to match against.
        /// </summary>
        public static string activity_match_input {
            get {
                return ResourceManager.GetString("activity_match_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regular expression to match.
        /// </summary>
        public static string activity_match_pattern {
            get {
                return ResourceManager.GetString("activity_match_pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with this string.
        /// </summary>
        public static string activity_match_replacement {
            get {
                return ResourceManager.GetString("activity_match_replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New DataTable variable.
        /// </summary>
        public static string activity_new_datatable {
            get {
                return ResourceManager.GetString("activity_new_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select excel file to read.
        /// </summary>
        public static string activity_readexcel_hint {
            get {
                return ResourceManager.GetString("activity_readexcel_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select JSON file to read.
        /// </summary>
        public static string activity_readjson_hint {
            get {
                return ResourceManager.GetString("activity_readjson_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select PDF file to read.
        /// </summary>
        public static string activity_readpdf_hint {
            get {
                return ResourceManager.GetString("activity_readpdf_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected File.
        /// </summary>
        public static string activity_selectfile_hint {
            get {
                return ResourceManager.GetString("activity_selectfile_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Folder.
        /// </summary>
        public static string activity_selectfolder_hint {
            get {
                return ResourceManager.GetString("activity_selectfolder_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments to be parsed the the executable.
        /// </summary>
        public static string activity_startprocess_arguments_hint {
            get {
                return ResourceManager.GetString("activity_startprocess_arguments_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full filename and path to the executable to start.
        /// </summary>
        public static string activity_startprocess_filename_hint {
            get {
                return ResourceManager.GetString("activity_startprocess_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSV file to write to.
        /// </summary>
        public static string activity_writecsv_hint {
            get {
                return ResourceManager.GetString("activity_writecsv_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select excel file to write to.
        /// </summary>
        public static string activity_writeexcel_hint {
            get {
                return ResourceManager.GetString("activity_writeexcel_hint", resourceCulture);
            }
        }
    }
}
