//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Windows.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop action.
        /// </summary>
        public static string activity_getelement_loopaction {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this, once done processing each result, then reruns the selector and looks for new items.
        /// </summary>
        public static string activity_getelement_loopaction_tooltop {
            get {
                return ResourceManager.GetString("activity_getelement_loopaction_tooltop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an Windows UI element based on selector.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string detector_button_highlight {
            get {
                return ResourceManager.GetString("detector_button_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string detector_button_open_selector {
            get {
                return ResourceManager.GetString("detector_button_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string detector_button_select {
            get {
                return ResourceManager.GetString("detector_button_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string detector_name {
            get {
                return ResourceManager.GetString("detector_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string detector_selector {
            get {
                return ResourceManager.GetString("detector_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable caching of elements for faster automation at the expense of ram.
        /// </summary>
        public static string enable_cache_help {
            get {
                return ResourceManager.GetString("enable_cache_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string getelement_drop_hint {
            get {
                return ResourceManager.GetString("getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string getelement_highlight {
            get {
                return ResourceManager.GetString("getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string getelement_open_selector {
            get {
                return ResourceManager.GetString("getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow multiple hits.
        /// </summary>
        public static string plugin_allow_multiple_hits {
            get {
                return ResourceManager.GetString("plugin_allow_multiple_hits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow an element selector in a selector to find more than one child.
        /// </summary>
        public static string plugin_allow_multiple_hits_help {
            get {
                return ResourceManager.GetString("plugin_allow_multiple_hits_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable caching.
        /// </summary>
        public static string plugin_enable_cache {
            get {
                return ResourceManager.GetString("plugin_enable_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum properties.
        /// </summary>
        public static string plugin_enum_properties {
            get {
                return ResourceManager.GetString("plugin_enum_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test each selector element for the minimum required amount of properties needed.
        /// </summary>
        public static string plugin_enum_properties_help {
            get {
                return ResourceManager.GetString("plugin_enum_properties_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get elements in different thread.
        /// </summary>
        public static string plugin_get_elements_in_different_thread {
            get {
                return ResourceManager.GetString("plugin_get_elements_in_different_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetElement uses another thread while searching, to avoid locks if selector finds robot.
        /// </summary>
        public static string plugin_get_elements_in_different_thread_help {
            get {
                return ResourceManager.GetString("plugin_get_elements_in_different_thread_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search descendants.
        /// </summary>
        public static string plugin_search_descendants {
            get {
                return ResourceManager.GetString("plugin_search_descendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow using &quot;partial&quot; selectors that is alow shorter, but can be slow with many ui elements.
        /// </summary>
        public static string plugin_search_descendants_help {
            get {
                return ResourceManager.GetString("plugin_search_descendants_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse selector both ways.
        /// </summary>
        public static string plugin_traverse_selector_both_ways {
            get {
                return ResourceManager.GetString("plugin_traverse_selector_both_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traverse UI tree both ways to filter out ghost selector elements.
        /// </summary>
        public static string plugin_traverse_selector_both_ways_help {
            get {
                return ResourceManager.GetString("plugin_traverse_selector_both_ways_help", resourceCulture);
            }
        }
    }
}
