//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Java.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Java.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string detector_highlight {
            get {
                return ResourceManager.GetString("detector_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string detector_name {
            get {
                return ResourceManager.GetString("detector_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string detector_open_selector {
            get {
                return ResourceManager.GetString("detector_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string detector_select {
            get {
                return ResourceManager.GetString("detector_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string detector_selector {
            get {
                return ResourceManager.GetString("detector_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto launch.
        /// </summary>
        public static string plugin_auto_launch_java_bridge {
            get {
                return ResourceManager.GetString("plugin_auto_launch_java_bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto launch java bridge application when robot is running.
        /// </summary>
        public static string plugin_auto_launch_java_bridge_help {
            get {
                return ResourceManager.GetString("plugin_auto_launch_java_bridge_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch java bridge.
        /// </summary>
        public static string plugin_launch_java_bridge {
            get {
                return ResourceManager.GetString("plugin_launch_java_bridge", resourceCulture);
            }
        }
    }
}
