//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Updater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Updater.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string main_button_install {
            get {
                return ResourceManager.GetString("main_button_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string main_button_launch {
            get {
                return ResourceManager.GetString("main_button_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch OpenRPA.
        /// </summary>
        public static string main_button_launch_hint {
            get {
                return ResourceManager.GetString("main_button_launch_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string main_button_reinstall {
            get {
                return ResourceManager.GetString("main_button_reinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string main_button_search {
            get {
                return ResourceManager.GetString("main_button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for activities.
        /// </summary>
        public static string main_button_search_hint {
            get {
                return ResourceManager.GetString("main_button_search_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string main_button_search_text {
            get {
                return ResourceManager.GetString("main_button_search_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string main_button_uninstall {
            get {
                return ResourceManager.GetString("main_button_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all.
        /// </summary>
        public static string main_button_update_all {
            get {
                return ResourceManager.GetString("main_button_update_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all.
        /// </summary>
        public static string main_button_update_all_hint {
            get {
                return ResourceManager.GetString("main_button_update_all_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string main_button_upgrade {
            get {
                return ResourceManager.GetString("main_button_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string main_label_authors {
            get {
                return ResourceManager.GetString("main_label_authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string main_label_description {
            get {
                return ResourceManager.GetString("main_label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string main_label_id {
            get {
                return ResourceManager.GetString("main_label_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string main_label_latestversion {
            get {
                return ResourceManager.GetString("main_label_latestversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string main_label_summary {
            get {
                return ResourceManager.GetString("main_label_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string main_label_tags {
            get {
                return ResourceManager.GetString("main_label_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string main_label_version {
            get {
                return ResourceManager.GetString("main_label_version", resourceCulture);
            }
        }
    }
}
