//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variables.
        /// </summary>
        public static string activity_add_variables {
            get {
                return ResourceManager.GetString("activity_add_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate Mouse.
        /// </summary>
        public static string activity_animatemouse {
            get {
                return ResourceManager.GetString("activity_animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibly move the mouse, instead of instantly moving it to the destination.
        /// </summary>
        public static string activity_animatemouse_help {
            get {
                return ResourceManager.GetString("activity_animatemouse_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate Move.
        /// </summary>
        public static string activity_animatemove {
            get {
                return ResourceManager.GetString("activity_animatemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibly move the window, instead of instantly moving it to the destination.
        /// </summary>
        public static string activity_animatemove_help {
            get {
                return ResourceManager.GetString("activity_animatemove_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking.
        /// </summary>
        public static string activity_blocking {
            get {
                return ResourceManager.GetString("activity_blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block execution until the complete.
        /// </summary>
        public static string activity_blocking_help {
            get {
                return ResourceManager.GetString("activity_blocking_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Running.
        /// </summary>
        public static string activity_checkrunning {
            get {
                return ResourceManager.GetString("activity_checkrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if application is already running using the selector, if set to false, will launch a new application no matter what.
        /// </summary>
        public static string activity_checkrunning_help {
            get {
                return ResourceManager.GetString("activity_checkrunning_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Element.
        /// </summary>
        public static string activity_clickelement {
            get {
                return ResourceManager.GetString("activity_clickelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an element found with GetElement.
        /// </summary>
        public static string activity_clickelement_tooltip {
            get {
                return ResourceManager.GetString("activity_clickelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string activity_closeapplication {
            get {
                return ResourceManager.GetString("activity_closeapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find application based on a UI selector and then closes the Application.
        /// </summary>
        public static string activity_closeapplication_tooltip {
            get {
                return ResourceManager.GetString("activity_closeapplication_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Out.
        /// </summary>
        public static string activity_commentout {
            get {
                return ResourceManager.GetString("activity_commentout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore everything inside this Acitvity, handy for quickly remarking something out.
        /// </summary>
        public static string activity_commentout_tooltip {
            get {
                return ResourceManager.GetString("activity_commentout_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Clipboard.
        /// </summary>
        public static string activity_copyclipboard {
            get {
                return ResourceManager.GetString("activity_copyclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy content of Clipboard into a variable.
        /// </summary>
        public static string activity_copyclipboard_tooltip {
            get {
                return ResourceManager.GetString("activity_copyclipboard_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Table.
        /// </summary>
        public static string activity_datatable {
            get {
                return ResourceManager.GetString("activity_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataTable to work with.
        /// </summary>
        public static string activity_datatable_help {
            get {
                return ResourceManager.GetString("activity_datatable_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data View.
        /// </summary>
        public static string activity_dataview {
            get {
                return ResourceManager.GetString("activity_dataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DateView to work with.
        /// </summary>
        public static string activity_dataview_help {
            get {
                return ResourceManager.GetString("activity_dataview_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detector.
        /// </summary>
        public static string activity_detector {
            get {
                return ResourceManager.GetString("activity_detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will wait for this detector to trigger, then the workflow will continue.
        /// </summary>
        public static string activity_detector_help {
            get {
                return ResourceManager.GetString("activity_detector_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puts workflow in idle mode, waiting on selected detector to trigger.
        /// </summary>
        public static string activity_detector_tooltip {
            get {
                return ResourceManager.GetString("activity_detector_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname inside the workflow designer.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click.
        /// </summary>
        public static string activity_doubleclick {
            get {
                return ResourceManager.GetString("activity_doubleclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do a double click instead of single click.
        /// </summary>
        public static string activity_doubleclick_help {
            get {
                return ResourceManager.GetString("activity_doubleclick_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string activity_duration {
            get {
                return ResourceManager.GetString("activity_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will run for the duration.
        /// </summary>
        public static string activity_duration_help {
            get {
                return ResourceManager.GetString("activity_duration_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string activity_element {
            get {
                return ResourceManager.GetString("activity_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on this element, the return type of all GetElement activites and some others.
        /// </summary>
        public static string activity_element_help {
            get {
                return ResourceManager.GetString("activity_element_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string activity_force {
            get {
                return ResourceManager.GetString("activity_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcefully do the action.
        /// </summary>
        public static string activity_force_help {
            get {
                return ResourceManager.GetString("activity_force_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreach DataRow.
        /// </summary>
        public static string activity_foreachdatarow {
            get {
                return ResourceManager.GetString("activity_foreachdatarow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate through each row inside a DataTable.
        /// </summary>
        public static string activity_foreachdatarow_tooltip {
            get {
                return ResourceManager.GetString("activity_foreachdatarow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string activity_height {
            get {
                return ResourceManager.GetString("activity_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, will move the window to this location.
        /// </summary>
        public static string activity_height_help {
            get {
                return ResourceManager.GetString("activity_height_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_highlight {
            get {
                return ResourceManager.GetString("activity_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Element.
        /// </summary>
        public static string activity_highlightelement {
            get {
                return ResourceManager.GetString("activity_highlightelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight an element found with GetElement.
        /// </summary>
        public static string activity_highlightelement_tooltip {
            get {
                return ResourceManager.GetString("activity_highlightelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Errors.
        /// </summary>
        public static string activity_ignoreerrors {
            get {
                return ResourceManager.GetString("activity_ignoreerrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error occurs, will ignore it an continue.
        /// </summary>
        public static string activity_ignoreerrors_help {
            get {
                return ResourceManager.GetString("activity_ignoreerrors_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Result.
        /// </summary>
        public static string activity_imageresult {
            get {
                return ResourceManager.GetString("activity_imageresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the result as an image.
        /// </summary>
        public static string activity_imageresult_help {
            get {
                return ResourceManager.GetString("activity_imageresult_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Clipboard.
        /// </summary>
        public static string activity_insertclipboard {
            get {
                return ResourceManager.GetString("activity_insertclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new content into the users Clipboard buffer.
        /// </summary>
        public static string activity_insertclipboard_tooltip {
            get {
                return ResourceManager.GetString("activity_insertclipboard_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke OpenFlow.
        /// </summary>
        public static string activity_invokeopenflow {
            get {
                return ResourceManager.GetString("activity_invokeopenflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke a workflow in node registered for RPA usage inside OpenFlow.
        /// </summary>
        public static string activity_invokeopenflow_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeopenflow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke OpenRPA.
        /// </summary>
        public static string activity_invokeopenrpa {
            get {
                return ResourceManager.GetString("activity_invokeopenrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke a local OpenRPA Workflow.
        /// </summary>
        public static string activity_invokeopenrpa_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeopenrpa_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Remote OpenRPA.
        /// </summary>
        public static string activity_invokeremoteopenrpa {
            get {
                return ResourceManager.GetString("activity_invokeremoteopenrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke a OpenRPA Workflow on a remote Robot.
        /// </summary>
        public static string activity_invokeremoteopenrpa_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeremoteopenrpa_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Modifiers.
        /// </summary>
        public static string activity_keymodifiers {
            get {
                return ResourceManager.GetString("activity_keymodifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold this key down, while clicking, only works if Virtual click is disabled.
        /// </summary>
        public static string activity_keymodifiers_help {
            get {
                return ResourceManager.GetString("activity_keymodifiers_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Button.
        /// </summary>
        public static string activity_mousebutton {
            get {
                return ResourceManager.GetString("activity_mousebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse button to click with.
        /// </summary>
        public static string activity_mousebutton_help {
            get {
                return ResourceManager.GetString("activity_mousebutton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Mouse.
        /// </summary>
        public static string activity_movemouse {
            get {
                return ResourceManager.GetString("activity_movemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse cursor to a location relative to an element found with GetElement (or desktop if no element supplied).
        /// </summary>
        public static string activity_movemouse_tooltip {
            get {
                return ResourceManager.GetString("activity_movemouse_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        public static string activity_offsetx {
            get {
                return ResourceManager.GetString("activity_offsetx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click with this offset inside the element.
        /// </summary>
        public static string activity_offsetx_help {
            get {
                return ResourceManager.GetString("activity_offsetx_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        public static string activity_offsety {
            get {
                return ResourceManager.GetString("activity_offsety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click with this offset inside the element.
        /// </summary>
        public static string activity_offsety_help {
            get {
                return ResourceManager.GetString("activity_offsety_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_open_selector {
            get {
                return ResourceManager.GetString("activity_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Application.
        /// </summary>
        public static string activity_openapplication {
            get {
                return ResourceManager.GetString("activity_openapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Windows element based on a selector, and give it focus, if not found start the application.
        /// </summary>
        public static string activity_openapplication_tooltip {
            get {
                return ResourceManager.GetString("activity_openapplication_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Wait.
        /// </summary>
        public static string activity_postwait {
            get {
                return ResourceManager.GetString("activity_postwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait this amount of time, after doing the click, help full one applications that can be very slow to react on clicks.
        /// </summary>
        public static string activity_postwait_help {
            get {
                return ResourceManager.GetString("activity_postwait_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string activity_result {
            get {
                return ResourceManager.GetString("activity_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the result into this variable.
        /// </summary>
        public static string activity_result_help {
            get {
                return ResourceManager.GetString("activity_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string activity_select_element {
            get {
                return ResourceManager.GetString("activity_select_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string activity_selector {
            get {
                return ResourceManager.GetString("activity_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector used to find the element(s), supports mapping workflow variables by using {{variablename}}.
        /// </summary>
        public static string activity_selector_help {
            get {
                return ResourceManager.GetString("activity_selector_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ctrl+C.
        /// </summary>
        public static string activity_sendctrlc {
            get {
                return ResourceManager.GetString("activity_sendctrlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Ctrl+C before trying to copy the Clipboard Content.
        /// </summary>
        public static string activity_sendctrlc_help {
            get {
                return ResourceManager.GetString("activity_sendctrlc_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string activity_showballontop_message {
            get {
                return ResourceManager.GetString("activity_showballontop_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to show.
        /// </summary>
        public static string activity_showballontop_message_hint {
            get {
                return ResourceManager.GetString("activity_showballontop_message_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string activity_showballontop_title {
            get {
                return ResourceManager.GetString("activity_showballontop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title on bollanmessage.
        /// </summary>
        public static string activity_showballontop_title_hint {
            get {
                return ResourceManager.GetString("activity_showballontop_title_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Balloon Tip.
        /// </summary>
        public static string activity_showballoontip {
            get {
                return ResourceManager.GetString("activity_showballoontip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a small ballontip near the system tray, will respect OS message center settings.
        /// </summary>
        public static string activity_showballoontip_tooltip {
            get {
                return ResourceManager.GetString("activity_showballoontip_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Result.
        /// </summary>
        public static string activity_stringresult {
            get {
                return ResourceManager.GetString("activity_stringresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the result as a string.
        /// </summary>
        public static string activity_stringresult_help {
            get {
                return ResourceManager.GetString("activity_stringresult_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string activity_target {
            get {
                return ResourceManager.GetString("activity_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target user or role.
        /// </summary>
        public static string activity_target_help {
            get {
                return ResourceManager.GetString("activity_target_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_text {
            get {
                return ResourceManager.GetString("activity_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_timeout {
            get {
                return ResourceManager.GetString("activity_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait this long before giving up and either failing or continuing depending on other settings.
        /// </summary>
        public static string activity_timeout_help {
            get {
                return ResourceManager.GetString("activity_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Text.
        /// </summary>
        public static string activity_typetext {
            get {
                return ResourceManager.GetString("activity_typetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send keyboard strokes to what ever that has focus, should only be used by recorder.
        /// </summary>
        public static string activity_typetext_tooltip {
            get {
                return ResourceManager.GetString("activity_typetext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Click.
        /// </summary>
        public static string activity_virtualclick {
            get {
                return ResourceManager.GetString("activity_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try and do a Virtual click instead of using the mouse, not all elements supports this.
        /// </summary>
        public static string activity_virtualclick_help {
            get {
                return ResourceManager.GetString("activity_virtualclick_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait until Completed.
        /// </summary>
        public static string activity_waitforcompleted {
            get {
                return ResourceManager.GetString("activity_waitforcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Completion before continuing with workflow.
        /// </summary>
        public static string activity_waitforcompleted_help {
            get {
                return ResourceManager.GetString("activity_waitforcompleted_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string activity_width {
            get {
                return ResourceManager.GetString("activity_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, will move the window to this location.
        /// </summary>
        public static string activity_width_help {
            get {
                return ResourceManager.GetString("activity_width_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        public static string activity_workflow {
            get {
                return ResourceManager.GetString("activity_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this workflow.
        /// </summary>
        public static string activity_workflow_help {
            get {
                return ResourceManager.GetString("activity_workflow_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string activity_x {
            get {
                return ResourceManager.GetString("activity_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, will move the window to this location.
        /// </summary>
        public static string activity_x_help {
            get {
                return ResourceManager.GetString("activity_x_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string activity_y {
            get {
                return ResourceManager.GetString("activity_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, will move the window to this location.
        /// </summary>
        public static string activity_y_help {
            get {
                return ResourceManager.GetString("activity_y_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Animate Mouse.
        /// </summary>
        public static string animatemouse {
            get {
                return ResourceManager.GetString("animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser addons.
        /// </summary>
        public static string browseraddons {
            get {
                return ResourceManager.GetString("browseraddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel key.
        /// </summary>
        public static string cancelkey {
            get {
                return ResourceManager.GetString("cancelkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        public static string chrome {
            get {
                return ResourceManager.GetString("chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Click PostWait.
        /// </summary>
        public static string clickpostwait {
            get {
                return ResourceManager.GetString("clickpostwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ID.
        /// </summary>
        public static string copyid {
            get {
                return ResourceManager.GetString("copyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Relative Filename.
        /// </summary>
        public static string copyrelativefilename {
            get {
                return ResourceManager.GetString("copyrelativefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment out.
        /// </summary>
        public static string designer_menu_commentout {
            get {
                return ResourceManager.GetString("designer_menu_commentout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run from here.
        /// </summary>
        public static string designer_menu_runfromhere {
            get {
                return ResourceManager.GetString("designer_menu_runfromhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this activity.
        /// </summary>
        public static string designer_menu_runthis {
            get {
                return ResourceManager.GetString("designer_menu_runthis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomment.
        /// </summary>
        public static string designer_menu_uncomment {
            get {
                return ResourceManager.GetString("designer_menu_uncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors.
        /// </summary>
        public static string detectors {
            get {
                return ResourceManager.GetString("detectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string dock_logging {
            get {
                return ResourceManager.GetString("dock_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string dock_output {
            get {
                return ResourceManager.GetString("dock_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string dock_properties {
            get {
                return ResourceManager.GetString("dock_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        public static string dock_snippets {
            get {
                return ResourceManager.GetString("dock_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string dock_toolbox {
            get {
                return ResourceManager.GetString("dock_toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Instances.
        /// </summary>
        public static string dock_workflowinstances {
            get {
                return ResourceManager.GetString("dock_workflowinstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string exitapplication {
            get {
                return ResourceManager.GetString("exitapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        public static string firefox {
            get {
                return ResourceManager.GetString("firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string logging {
            get {
                return ResourceManager.GetString("logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string main_reload {
            get {
                return ResourceManager.GetString("main_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record directly into designer.
        /// </summary>
        public static string main_settings_recording_add_to_designer {
            get {
                return ResourceManager.GetString("main_settings_recording_add_to_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string mainnew {
            get {
                return ResourceManager.GetString("mainnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRPA.
        /// </summary>
        public static string maintitle {
            get {
                return ResourceManager.GetString("maintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workflow.
        /// </summary>
        public static string newworkflow {
            get {
                return ResourceManager.GetString("newworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeRED.
        /// </summary>
        public static string nodered {
            get {
                return ResourceManager.GetString("nodered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string open_created {
            get {
                return ResourceManager.GetString("open_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string open_createdby {
            get {
                return ResourceManager.GetString("open_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string open_edit {
            get {
                return ResourceManager.GetString("open_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit XAML.
        /// </summary>
        public static string open_edit_xaml {
            get {
                return ResourceManager.GetString("open_edit_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified at.
        /// </summary>
        public static string open_modified {
            get {
                return ResourceManager.GetString("open_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        public static string open_modifiedby {
            get {
                return ResourceManager.GetString("open_modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string open_name {
            get {
                return ResourceManager.GetString("open_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializable.
        /// </summary>
        public static string open_serializable {
            get {
                return ResourceManager.GetString("open_serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string open_state {
            get {
                return ResourceManager.GetString("open_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenFlow.
        /// </summary>
        public static string openflow {
            get {
                return ResourceManager.GetString("openflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRPA.
        /// </summary>
        public static string openrpa {
            get {
                return ResourceManager.GetString("openrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string permissions_delete {
            get {
                return ResourceManager.GetString("permissions_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke.
        /// </summary>
        public static string permissions_invoke {
            get {
                return ResourceManager.GetString("permissions_invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string permissions_read {
            get {
                return ResourceManager.GetString("permissions_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string permissions_update {
            get {
                return ResourceManager.GetString("permissions_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string permissionswindow_delete {
            get {
                return ResourceManager.GetString("permissionswindow_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string permissionswindow_new {
            get {
                return ResourceManager.GetString("permissionswindow_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder plugins.
        /// </summary>
        public static string recorderplugins {
            get {
                return ResourceManager.GetString("recorderplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Overlay.
        /// </summary>
        public static string recordingoverlay {
            get {
                return ResourceManager.GetString("recordingoverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ribbon_search {
            get {
                return ResourceManager.GetString("ribbon_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run plugins.
        /// </summary>
        public static string runplugins {
            get {
                return ResourceManager.GetString("runplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string runtime {
            get {
                return ResourceManager.GetString("runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string selector {
            get {
                return ResourceManager.GetString("selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector Verbose.
        /// </summary>
        public static string selectorverbose {
            get {
                return ResourceManager.GetString("selectorverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings File.
        /// </summary>
        public static string settingsfile {
            get {
                return ResourceManager.GetString("settingsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Motion.
        /// </summary>
        public static string slowmotion {
            get {
                return ResourceManager.GetString("slowmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string status_disconnected {
            get {
                return ResourceManager.GetString("status_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract.
        /// </summary>
        public static string tesseract {
            get {
                return ResourceManager.GetString("tesseract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type.
        /// </summary>
        public static string tools_change_type {
            get {
                return ResourceManager.GetString("tools_change_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Animate.
        /// </summary>
        public static string tools_swap_animate {
            get {
                return ResourceManager.GetString("tools_swap_animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap SendKeys.
        /// </summary>
        public static string tools_swap_sendkeys {
            get {
                return ResourceManager.GetString("tools_swap_sendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Virtual Clicking.
        /// </summary>
        public static string tools_swap_virtualclick {
            get {
                return ResourceManager.GetString("tools_swap_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        public static string uilanguage {
            get {
                return ResourceManager.GetString("uilanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SendKeys.
        /// </summary>
        public static string usesendkeys {
            get {
                return ResourceManager.GetString("usesendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Virtual Clicks.
        /// </summary>
        public static string usevirtualclicks {
            get {
                return ResourceManager.GetString("usevirtualclicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string verbose {
            get {
                return ResourceManager.GetString("verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Tracking.
        /// </summary>
        public static string visualtracking {
            get {
                return ResourceManager.GetString("visualtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
