//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add variables.
        /// </summary>
        public static string activity_add_variables {
            get {
                return ResourceManager.GetString("activity_add_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click to view.
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_highlight {
            get {
                return ResourceManager.GetString("activity_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Selector.
        /// </summary>
        public static string activity_open_selector {
            get {
                return ResourceManager.GetString("activity_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Element.
        /// </summary>
        public static string activity_select_element {
            get {
                return ResourceManager.GetString("activity_select_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Animate Mouse.
        /// </summary>
        public static string animatemouse {
            get {
                return ResourceManager.GetString("animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser addons.
        /// </summary>
        public static string browseraddons {
            get {
                return ResourceManager.GetString("browseraddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel key.
        /// </summary>
        public static string cancelkey {
            get {
                return ResourceManager.GetString("cancelkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        public static string chrome {
            get {
                return ResourceManager.GetString("chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Click PostWait.
        /// </summary>
        public static string clickpostwait {
            get {
                return ResourceManager.GetString("clickpostwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detectors.
        /// </summary>
        public static string detectors {
            get {
                return ResourceManager.GetString("detectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string dock_logging {
            get {
                return ResourceManager.GetString("dock_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string dock_output {
            get {
                return ResourceManager.GetString("dock_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string dock_properties {
            get {
                return ResourceManager.GetString("dock_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets.
        /// </summary>
        public static string dock_snippets {
            get {
                return ResourceManager.GetString("dock_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string dock_toolbox {
            get {
                return ResourceManager.GetString("dock_toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string exitapplication {
            get {
                return ResourceManager.GetString("exitapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        public static string firefox {
            get {
                return ResourceManager.GetString("firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string logging {
            get {
                return ResourceManager.GetString("logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string main_reload {
            get {
                return ResourceManager.GetString("main_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record directly into designer.
        /// </summary>
        public static string main_settings_recording_add_to_designer {
            get {
                return ResourceManager.GetString("main_settings_recording_add_to_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string mainnew {
            get {
                return ResourceManager.GetString("mainnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRPA.
        /// </summary>
        public static string maintitle {
            get {
                return ResourceManager.GetString("maintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Workflow.
        /// </summary>
        public static string newworkflow {
            get {
                return ResourceManager.GetString("newworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeRED.
        /// </summary>
        public static string nodered {
            get {
                return ResourceManager.GetString("nodered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string open_created {
            get {
                return ResourceManager.GetString("open_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string open_createdby {
            get {
                return ResourceManager.GetString("open_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string open_edit {
            get {
                return ResourceManager.GetString("open_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit XAML.
        /// </summary>
        public static string open_edit_xaml {
            get {
                return ResourceManager.GetString("open_edit_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified at.
        /// </summary>
        public static string open_modified {
            get {
                return ResourceManager.GetString("open_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by.
        /// </summary>
        public static string open_modifiedby {
            get {
                return ResourceManager.GetString("open_modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string open_name {
            get {
                return ResourceManager.GetString("open_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializable.
        /// </summary>
        public static string open_serializable {
            get {
                return ResourceManager.GetString("open_serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string open_state {
            get {
                return ResourceManager.GetString("open_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenFlow.
        /// </summary>
        public static string openflow {
            get {
                return ResourceManager.GetString("openflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRPA.
        /// </summary>
        public static string openrpa {
            get {
                return ResourceManager.GetString("openrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string permissions_delete {
            get {
                return ResourceManager.GetString("permissions_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke.
        /// </summary>
        public static string permissions_invoke {
            get {
                return ResourceManager.GetString("permissions_invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string permissions_read {
            get {
                return ResourceManager.GetString("permissions_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string permissions_update {
            get {
                return ResourceManager.GetString("permissions_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string permissionswindow_delete {
            get {
                return ResourceManager.GetString("permissionswindow_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string permissionswindow_new {
            get {
                return ResourceManager.GetString("permissionswindow_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder plugins.
        /// </summary>
        public static string recorderplugins {
            get {
                return ResourceManager.GetString("recorderplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Overlay.
        /// </summary>
        public static string recordingoverlay {
            get {
                return ResourceManager.GetString("recordingoverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ribbon_search {
            get {
                return ResourceManager.GetString("ribbon_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run plugins.
        /// </summary>
        public static string runplugins {
            get {
                return ResourceManager.GetString("runplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string runtime {
            get {
                return ResourceManager.GetString("runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string selector {
            get {
                return ResourceManager.GetString("selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector Verbose.
        /// </summary>
        public static string selectorverbose {
            get {
                return ResourceManager.GetString("selectorverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings File.
        /// </summary>
        public static string settingsfile {
            get {
                return ResourceManager.GetString("settingsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Motion.
        /// </summary>
        public static string slowmotion {
            get {
                return ResourceManager.GetString("slowmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string status_disconnected {
            get {
                return ResourceManager.GetString("status_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesseract.
        /// </summary>
        public static string tesseract {
            get {
                return ResourceManager.GetString("tesseract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type.
        /// </summary>
        public static string tools_change_type {
            get {
                return ResourceManager.GetString("tools_change_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Animate.
        /// </summary>
        public static string tools_swap_animate {
            get {
                return ResourceManager.GetString("tools_swap_animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap SendKeys.
        /// </summary>
        public static string tools_swap_sendkeys {
            get {
                return ResourceManager.GetString("tools_swap_sendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Virtual Clicking.
        /// </summary>
        public static string tools_swap_virtualclick {
            get {
                return ResourceManager.GetString("tools_swap_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SendKeys.
        /// </summary>
        public static string usesendkeys {
            get {
                return ResourceManager.GetString("usesendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Virtual Clicks.
        /// </summary>
        public static string usevirtualclicks {
            get {
                return ResourceManager.GetString("usevirtualclicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string verbose {
            get {
                return ResourceManager.GetString("verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Tracking.
        /// </summary>
        public static string visualtracking {
            get {
                return ResourceManager.GetString("visualtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
