//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Image.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Image.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname inside the workflow designer.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string activity_element {
            get {
                return ResourceManager.GetString("activity_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work on this element, the return type of all GetElement activites and some others.
        /// </summary>
        public static string activity_element_help {
            get {
                return ResourceManager.GetString("activity_element_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Color.
        /// </summary>
        public static string activity_getcolor {
            get {
                return ResourceManager.GetString("activity_getcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get color at specefied cordinates. .
        /// </summary>
        public static string activity_getcolor_tooltip {
            get {
                return ResourceManager.GetString("activity_getcolor_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Element.
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Limit.
        /// </summary>
        public static string activity_getelement_process_limit {
            get {
                return ResourceManager.GetString("activity_getelement_process_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string activity_getelement_select {
            get {
                return ResourceManager.GetString("activity_getelement_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find an image on the screen or inside a specific application window.
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Image.
        /// </summary>
        public static string activity_getimage {
            get {
                return ResourceManager.GetString("activity_getimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getimage_drop_hint {
            get {
                return ResourceManager.GetString("activity_getimage_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getimage_highlight {
            get {
                return ResourceManager.GetString("activity_getimage_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string activity_getimage_select {
            get {
                return ResourceManager.GetString("activity_getimage_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an image of the screen relative from another image or element found with GetElement.
        /// </summary>
        public static string activity_getimage_tooltip {
            get {
                return ResourceManager.GetString("activity_getimage_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text.
        /// </summary>
        public static string activity_gettext {
            get {
                return ResourceManager.GetString("activity_gettext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_gettext_drop_hint {
            get {
                return ResourceManager.GetString("activity_gettext_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit to.
        /// </summary>
        public static string activity_gettext_limit {
            get {
                return ResourceManager.GetString("activity_gettext_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search only for this word.
        /// </summary>
        public static string activity_gettext_limit_hint {
            get {
                return ResourceManager.GetString("activity_gettext_limit_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using OCR get all text from a image, can be limited to a specific word or sentence.
        /// </summary>
        public static string activity_gettext_tooltip {
            get {
                return ResourceManager.GetString("activity_gettext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_loadfile_drop_hint {
            get {
                return ResourceManager.GetString("activity_loadfile_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_loadfile_filename {
            get {
                return ResourceManager.GetString("activity_loadfile_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file to load.
        /// </summary>
        public static string activity_loadfile_filename_hint {
            get {
                return ResourceManager.GetString("activity_loadfile_filename_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From File.
        /// </summary>
        public static string activity_loadfromfile {
            get {
                return ResourceManager.GetString("activity_loadfromfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an image from a file and return an ImageElement.
        /// </summary>
        public static string activity_loadfromfile_tooltip {
            get {
                return ResourceManager.GetString("activity_loadfromfile_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        public static string activity_offsetx {
            get {
                return ResourceManager.GetString("activity_offsetx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click with this offset inside the element.
        /// </summary>
        public static string activity_offsetx_help {
            get {
                return ResourceManager.GetString("activity_offsetx_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        public static string activity_offsety {
            get {
                return ResourceManager.GetString("activity_offsety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click with this offset inside the element.
        /// </summary>
        public static string activity_offsety_help {
            get {
                return ResourceManager.GetString("activity_offsety_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Window.
        /// </summary>
        public static string activity_printwindow {
            get {
                return ResourceManager.GetString("activity_printwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print an application window with specified window name even when screen is locked.
        /// </summary>
        public static string activity_printwindow_tooltip {
            get {
                return ResourceManager.GetString("activity_printwindow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Screenshot.
        /// </summary>
        public static string activity_takescreenshot {
            get {
                return ResourceManager.GetString("activity_takescreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot of the entire screen or a specific element found using Get Element.
        /// </summary>
        public static string activity_takescreenshot_tooltip {
            get {
                return ResourceManager.GetString("activity_takescreenshot_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse move time.
        /// </summary>
        public static string plugin_recording_mouse_move_time {
            get {
                return ResourceManager.GetString("plugin_recording_mouse_move_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing recording, move mouse away for X miliseconds before getting image.
        /// </summary>
        public static string plugin_recording_mouse_move_time_help {
            get {
                return ResourceManager.GetString("plugin_recording_mouse_move_time_help", resourceCulture);
            }
        }
    }
}
