//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Image.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Image.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Limit.
        /// </summary>
        public static string activity_getelement_process_limit {
            get {
                return ResourceManager.GetString("activity_getelement_process_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string activity_getelement_select {
            get {
                return ResourceManager.GetString("activity_getelement_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getimage_drop_hint {
            get {
                return ResourceManager.GetString("activity_getimage_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string activity_getimage_highlight {
            get {
                return ResourceManager.GetString("activity_getimage_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string activity_getimage_select {
            get {
                return ResourceManager.GetString("activity_getimage_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_gettext_drop_hint {
            get {
                return ResourceManager.GetString("activity_gettext_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit to.
        /// </summary>
        public static string activity_gettext_limit {
            get {
                return ResourceManager.GetString("activity_gettext_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search only for this word.
        /// </summary>
        public static string activity_gettext_limit_hint {
            get {
                return ResourceManager.GetString("activity_gettext_limit_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_loadfile_drop_hint {
            get {
                return ResourceManager.GetString("activity_loadfile_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string activity_loadfile_filename {
            get {
                return ResourceManager.GetString("activity_loadfile_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file to load.
        /// </summary>
        public static string activity_loadfile_filename_hint {
            get {
                return ResourceManager.GetString("activity_loadfile_filename_hint", resourceCulture);
            }
        }
    }
}
