//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.TerminalEmulator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.TerminalEmulator.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view.
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname.
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayname inside the workflow designer.
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop activity.
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text.
        /// </summary>
        public static string activity_gettext {
            get {
                return ResourceManager.GetString("activity_gettext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string activity_gettext_field {
            get {
                return ResourceManager.GetString("activity_gettext_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get text by field ( input field ).
        /// </summary>
        public static string activity_gettext_field_help {
            get {
                return ResourceManager.GetString("activity_gettext_field_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string activity_gettext_result {
            get {
                return ResourceManager.GetString("activity_gettext_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resulting text from field or string.
        /// </summary>
        public static string activity_gettext_result_help {
            get {
                return ResourceManager.GetString("activity_gettext_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string activity_gettext_string {
            get {
                return ResourceManager.GetString("activity_gettext_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get by string field.
        /// </summary>
        public static string activity_gettext_string_help {
            get {
                return ResourceManager.GetString("activity_gettext_string_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_gettext_timeout {
            get {
                return ResourceManager.GetString("activity_gettext_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while waiting on field or string to appear.
        /// </summary>
        public static string activity_gettext_timeout_help {
            get {
                return ResourceManager.GetString("activity_gettext_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text by field or string index.
        /// </summary>
        public static string activity_gettext_tooltip {
            get {
                return ResourceManager.GetString("activity_gettext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Keyboard.
        /// </summary>
        public static string activity_gettext_waitforkeyboard {
            get {
                return ResourceManager.GetString("activity_gettext_waitforkeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, will wait for keyboard to be unlocked before getting text.
        /// </summary>
        public static string activity_gettext_waitforkeyboard_help {
            get {
                return ResourceManager.GetString("activity_gettext_waitforkeyboard_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string activity_gettextat_column {
            get {
                return ResourceManager.GetString("activity_gettextat_column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column to start reading from ( X ).
        /// </summary>
        public static string activity_gettextat_column_help {
            get {
                return ResourceManager.GetString("activity_gettextat_column_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string activity_gettextat_length {
            get {
                return ResourceManager.GetString("activity_gettextat_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of charecter to read of the string.
        /// </summary>
        public static string activity_gettextat_length_help {
            get {
                return ResourceManager.GetString("activity_gettextat_length_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string activity_gettextat_result {
            get {
                return ResourceManager.GetString("activity_gettextat_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of read operation.
        /// </summary>
        public static string activity_gettextat_result_help {
            get {
                return ResourceManager.GetString("activity_gettextat_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string activity_gettextat_row {
            get {
                return ResourceManager.GetString("activity_gettextat_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row to start reading from ( Y ).
        /// </summary>
        public static string activity_gettextat_row_help {
            get {
                return ResourceManager.GetString("activity_gettextat_row_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_gettextat_timeout {
            get {
                return ResourceManager.GetString("activity_gettextat_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait this long for keyboard to be ready, if enabled.
        /// </summary>
        public static string activity_gettextat_timeout_help {
            get {
                return ResourceManager.GetString("activity_gettextat_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Keyboard.
        /// </summary>
        public static string activity_gettextat_waitforkeyboard {
            get {
                return ResourceManager.GetString("activity_gettextat_waitforkeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, will wait for keyboard to be unlocked before getting text.
        /// </summary>
        public static string activity_gettextat_waitforkeyboard_help {
            get {
                return ResourceManager.GetString("activity_gettextat_waitforkeyboard_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Text At.
        /// </summary>
        public static string activity_gettextatat {
            get {
                return ResourceManager.GetString("activity_gettextatat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read a certain number of charecter from the specefied location on the screen.
        /// </summary>
        public static string activity_gettextatat_tooltip {
            get {
                return ResourceManager.GetString("activity_gettextatat_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recorder.
        /// </summary>
        public static string activity_open_recorder {
            get {
                return ResourceManager.GetString("activity_open_recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder.
        /// </summary>
        public static string activity_recorder {
            get {
                return ResourceManager.GetString("activity_recorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Key.
        /// </summary>
        public static string activity_sendkey {
            get {
                return ResourceManager.GetString("activity_sendkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string activity_sendkey_key {
            get {
                return ResourceManager.GetString("activity_sendkey_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to send to terminal.
        /// </summary>
        public static string activity_sendkey_key_help {
            get {
                return ResourceManager.GetString("activity_sendkey_key_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_sendkey_timeout {
            get {
                return ResourceManager.GetString("activity_sendkey_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout while waiting for keyboard ready.
        /// </summary>
        public static string activity_sendkey_timeout_help {
            get {
                return ResourceManager.GetString("activity_sendkey_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send specific Key to terminal.
        /// </summary>
        public static string activity_sendkey_tooltip {
            get {
                return ResourceManager.GetString("activity_sendkey_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Keyboard.
        /// </summary>
        public static string activity_sendkey_waitforkeyboard {
            get {
                return ResourceManager.GetString("activity_sendkey_waitforkeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, will wait for keyboard to be unlocked before sending key.
        /// </summary>
        public static string activity_sendkey_waitforkeyboard_help {
            get {
                return ResourceManager.GetString("activity_sendkey_waitforkeyboard_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Text.
        /// </summary>
        public static string activity_sendtext {
            get {
                return ResourceManager.GetString("activity_sendtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_sendtext_text {
            get {
                return ResourceManager.GetString("activity_sendtext_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to send to the terminal.
        /// </summary>
        public static string activity_sendtext_text_help {
            get {
                return ResourceManager.GetString("activity_sendtext_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_sendtext_timeout {
            get {
                return ResourceManager.GetString("activity_sendtext_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait for the text to appear.
        /// </summary>
        public static string activity_sendtext_timeout_help {
            get {
                return ResourceManager.GetString("activity_sendtext_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send text to terminal.
        /// </summary>
        public static string activity_sendtext_tooltip {
            get {
                return ResourceManager.GetString("activity_sendtext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Keyboard.
        /// </summary>
        public static string activity_sendtext_waitforkeyboard {
            get {
                return ResourceManager.GetString("activity_sendtext_waitforkeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, will wait for keyboard to be unlocked before sending text.
        /// </summary>
        public static string activity_sendtext_waitforkeyboard_help {
            get {
                return ResourceManager.GetString("activity_sendtext_waitforkeyboard_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Text.
        /// </summary>
        public static string activity_settext {
            get {
                return ResourceManager.GetString("activity_settext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string activity_settext_field {
            get {
                return ResourceManager.GetString("activity_settext_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field index to set text for.
        /// </summary>
        public static string activity_settext_field_help {
            get {
                return ResourceManager.GetString("activity_settext_field_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_settext_text {
            get {
                return ResourceManager.GetString("activity_settext_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to assign to field.
        /// </summary>
        public static string activity_settext_text_help {
            get {
                return ResourceManager.GetString("activity_settext_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_settext_timeout {
            get {
                return ResourceManager.GetString("activity_settext_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Text will wait this long, for a field with this index to appear.
        /// </summary>
        public static string activity_settext_timeout_help {
            get {
                return ResourceManager.GetString("activity_settext_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set text to specefied field in a Terminal Session.
        /// </summary>
        public static string activity_settext_tooltip {
            get {
                return ResourceManager.GetString("activity_settext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Keyboard.
        /// </summary>
        public static string activity_settext_waitforkeyboard {
            get {
                return ResourceManager.GetString("activity_settext_waitforkeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, will wait for keyboard to be unlocked before setting text.
        /// </summary>
        public static string activity_settext_waitforkeyboard_help {
            get {
                return ResourceManager.GetString("activity_settext_waitforkeyboard_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Session.
        /// </summary>
        public static string activity_terminalsession {
            get {
                return ResourceManager.GetString("activity_terminalsession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide UI.
        /// </summary>
        public static string activity_terminalsession_hideui {
            get {
                return ResourceManager.GetString("activity_terminalsession_hideui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide terminal UI while running.
        /// </summary>
        public static string activity_terminalsession_hideui_help {
            get {
                return ResourceManager.GetString("activity_terminalsession_hideui_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string activity_terminalsession_hostname {
            get {
                return ResourceManager.GetString("activity_terminalsession_hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP of Mainframe to connnect to.
        /// </summary>
        public static string activity_terminalsession_hostname_help {
            get {
                return ResourceManager.GetString("activity_terminalsession_hostname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string activity_terminalsession_port {
            get {
                return ResourceManager.GetString("activity_terminalsession_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number of mainframe to connect to.
        /// </summary>
        public static string activity_terminalsession_port_help {
            get {
                return ResourceManager.GetString("activity_terminalsession_port_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermType.
        /// </summary>
        public static string activity_terminalsession_termtype {
            get {
                return ResourceManager.GetString("activity_terminalsession_termtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal type to repport to the mainframe ( and the type of mainframe parser to use ).
        /// </summary>
        public static string activity_terminalsession_termtype_help {
            get {
                return ResourceManager.GetString("activity_terminalsession_termtype_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_terminalsession_timeout {
            get {
                return ResourceManager.GetString("activity_terminalsession_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Timeout.
        /// </summary>
        public static string activity_terminalsession_timeout_help {
            get {
                return ResourceManager.GetString("activity_terminalsession_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait For Text.
        /// </summary>
        public static string activity_waitfortext {
            get {
                return ResourceManager.GetString("activity_waitfortext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string activity_waitfortext_found {
            get {
                return ResourceManager.GetString("activity_waitfortext_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If text was found before timeout, returns True.
        /// </summary>
        public static string activity_waitfortext_found_help {
            get {
                return ResourceManager.GetString("activity_waitfortext_found_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string activity_waitfortext_text {
            get {
                return ResourceManager.GetString("activity_waitfortext_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to look for.
        /// </summary>
        public static string activity_waitfortext_text_help {
            get {
                return ResourceManager.GetString("activity_waitfortext_text_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw.
        /// </summary>
        public static string activity_waitfortext_throw {
            get {
                return ResourceManager.GetString("activity_waitfortext_throw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throw exception if text was not found.
        /// </summary>
        public static string activity_waitfortext_throw_help {
            get {
                return ResourceManager.GetString("activity_waitfortext_throw_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string activity_waitfortext_timeout {
            get {
                return ResourceManager.GetString("activity_waitfortext_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long to wait for the text to appear.
        /// </summary>
        public static string activity_waitfortext_timeout_help {
            get {
                return ResourceManager.GetString("activity_waitfortext_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Text to appear somewhere on terminal screen.
        /// </summary>
        public static string activity_waitfortext_tooltip {
            get {
                return ResourceManager.GetString("activity_waitfortext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto close.
        /// </summary>
        public static string plugin_auto_close {
            get {
                return ResourceManager.GetString("plugin_auto_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After workflow completes or fails, auto close all terminal sessions ( usefull to disable doing development ).
        /// </summary>
        public static string plugin_auto_close_help {
            get {
                return ResourceManager.GetString("plugin_auto_close_help", resourceCulture);
            }
        }
    }
}
